// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/dynamicsrv.proto

package dynamicsrv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Dynamicsrv_Publish_FullMethodName               = "/dynamicsrv.Dynamicsrv/Publish"
	Dynamicsrv_Update_FullMethodName                = "/dynamicsrv.Dynamicsrv/Update"
	Dynamicsrv_List_FullMethodName                  = "/dynamicsrv.Dynamicsrv/List"
	Dynamicsrv_Info_FullMethodName                  = "/dynamicsrv.Dynamicsrv/Info"
	Dynamicsrv_Delete_FullMethodName                = "/dynamicsrv.Dynamicsrv/Delete"
	Dynamicsrv_RefreshSupclubDynamic_FullMethodName = "/dynamicsrv.Dynamicsrv/RefreshSupclubDynamic"
	Dynamicsrv_Praise_FullMethodName                = "/dynamicsrv.Dynamicsrv/Praise"
	Dynamicsrv_HasPraise_FullMethodName             = "/dynamicsrv.Dynamicsrv/HasPraise"
	Dynamicsrv_Collect_FullMethodName               = "/dynamicsrv.Dynamicsrv/Collect"
	Dynamicsrv_HasCollect_FullMethodName            = "/dynamicsrv.Dynamicsrv/HasCollect"
	Dynamicsrv_CollectList_FullMethodName           = "/dynamicsrv.Dynamicsrv/CollectList"
	Dynamicsrv_Focus_FullMethodName                 = "/dynamicsrv.Dynamicsrv/Focus"
	Dynamicsrv_HasFocus_FullMethodName              = "/dynamicsrv.Dynamicsrv/HasFocus"
	Dynamicsrv_Share_FullMethodName                 = "/dynamicsrv.Dynamicsrv/Share"
	Dynamicsrv_FocusList_FullMethodName             = "/dynamicsrv.Dynamicsrv/FocusList"
	Dynamicsrv_FansList_FullMethodName              = "/dynamicsrv.Dynamicsrv/FansList"
)

// DynamicsrvClient is the client API for Dynamicsrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamicsrvClient interface {
	// 发布动态
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 修改动态
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 动态列表
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// 动态详情
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// 删除动态
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 刷新部落动态（发布、更新、删除时，需要检查刷新部落与动态之间的关系
	RefreshSupclubDynamic(ctx context.Context, in *RefreshSupclubDynamicRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 点赞动态
	Praise(ctx context.Context, in *PraiseRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 该用户是否已点赞动态或点赞动态下的评论
	HasPraise(ctx context.Context, in *HasPraiseRequest, opts ...grpc.CallOption) (*HasPraiseResponse, error)
	// 收藏动态
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 该用户是否已收藏该动态
	HasCollect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*HasCollectResponse, error)
	// 用户收藏列表
	CollectList(ctx context.Context, in *CollectListRequest, opts ...grpc.CallOption) (*CollectListResponse, error)
	// 关注动态作者
	Focus(ctx context.Context, in *FocusRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 是否已经关注该作者
	HasFocus(ctx context.Context, in *FocusRequest, opts ...grpc.CallOption) (*HasFocusResponse, error)
	// 动态分享数,只增不减 -- 客户端上报main/data/callback
	Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*APICommonResponse, error)
	// 用户关注列表
	FocusList(ctx context.Context, in *FocusListRequest, opts ...grpc.CallOption) (*FocusListResponse, error)
	// 用户粉丝列表
	FansList(ctx context.Context, in *FansListRequest, opts ...grpc.CallOption) (*FansListResponse, error)
}

type dynamicsrvClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicsrvClient(cc grpc.ClientConnInterface) DynamicsrvClient {
	return &dynamicsrvClient{cc}
}

func (c *dynamicsrvClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Publish_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Info_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) RefreshSupclubDynamic(ctx context.Context, in *RefreshSupclubDynamicRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_RefreshSupclubDynamic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) Praise(ctx context.Context, in *PraiseRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Praise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) HasPraise(ctx context.Context, in *HasPraiseRequest, opts ...grpc.CallOption) (*HasPraiseResponse, error) {
	out := new(HasPraiseResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_HasPraise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Collect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) HasCollect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*HasCollectResponse, error) {
	out := new(HasCollectResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_HasCollect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) CollectList(ctx context.Context, in *CollectListRequest, opts ...grpc.CallOption) (*CollectListResponse, error) {
	out := new(CollectListResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_CollectList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) Focus(ctx context.Context, in *FocusRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Focus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) HasFocus(ctx context.Context, in *FocusRequest, opts ...grpc.CallOption) (*HasFocusResponse, error) {
	out := new(HasFocusResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_HasFocus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*APICommonResponse, error) {
	out := new(APICommonResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_Share_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) FocusList(ctx context.Context, in *FocusListRequest, opts ...grpc.CallOption) (*FocusListResponse, error) {
	out := new(FocusListResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_FocusList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicsrvClient) FansList(ctx context.Context, in *FansListRequest, opts ...grpc.CallOption) (*FansListResponse, error) {
	out := new(FansListResponse)
	err := c.cc.Invoke(ctx, Dynamicsrv_FansList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicsrvServer is the server API for Dynamicsrv service.
// All implementations must embed UnimplementedDynamicsrvServer
// for forward compatibility
type DynamicsrvServer interface {
	// 发布动态
	Publish(context.Context, *PublishRequest) (*APICommonResponse, error)
	// 修改动态
	Update(context.Context, *UpdateRequest) (*APICommonResponse, error)
	// 动态列表
	List(context.Context, *ListRequest) (*ListResponse, error)
	// 动态详情
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// 删除动态
	Delete(context.Context, *DeleteRequest) (*APICommonResponse, error)
	// 刷新部落动态（发布、更新、删除时，需要检查刷新部落与动态之间的关系
	RefreshSupclubDynamic(context.Context, *RefreshSupclubDynamicRequest) (*APICommonResponse, error)
	// 点赞动态
	Praise(context.Context, *PraiseRequest) (*APICommonResponse, error)
	// 该用户是否已点赞动态或点赞动态下的评论
	HasPraise(context.Context, *HasPraiseRequest) (*HasPraiseResponse, error)
	// 收藏动态
	Collect(context.Context, *CollectRequest) (*APICommonResponse, error)
	// 该用户是否已收藏该动态
	HasCollect(context.Context, *CollectRequest) (*HasCollectResponse, error)
	// 用户收藏列表
	CollectList(context.Context, *CollectListRequest) (*CollectListResponse, error)
	// 关注动态作者
	Focus(context.Context, *FocusRequest) (*APICommonResponse, error)
	// 是否已经关注该作者
	HasFocus(context.Context, *FocusRequest) (*HasFocusResponse, error)
	// 动态分享数,只增不减 -- 客户端上报main/data/callback
	Share(context.Context, *ShareRequest) (*APICommonResponse, error)
	// 用户关注列表
	FocusList(context.Context, *FocusListRequest) (*FocusListResponse, error)
	// 用户粉丝列表
	FansList(context.Context, *FansListRequest) (*FansListResponse, error)
	mustEmbedUnimplementedDynamicsrvServer()
}

// UnimplementedDynamicsrvServer must be embedded to have forward compatible implementations.
type UnimplementedDynamicsrvServer struct {
}

func (UnimplementedDynamicsrvServer) Publish(context.Context, *PublishRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedDynamicsrvServer) Update(context.Context, *UpdateRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDynamicsrvServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDynamicsrvServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedDynamicsrvServer) Delete(context.Context, *DeleteRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDynamicsrvServer) RefreshSupclubDynamic(context.Context, *RefreshSupclubDynamicRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSupclubDynamic not implemented")
}
func (UnimplementedDynamicsrvServer) Praise(context.Context, *PraiseRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Praise not implemented")
}
func (UnimplementedDynamicsrvServer) HasPraise(context.Context, *HasPraiseRequest) (*HasPraiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasPraise not implemented")
}
func (UnimplementedDynamicsrvServer) Collect(context.Context, *CollectRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedDynamicsrvServer) HasCollect(context.Context, *CollectRequest) (*HasCollectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasCollect not implemented")
}
func (UnimplementedDynamicsrvServer) CollectList(context.Context, *CollectListRequest) (*CollectListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectList not implemented")
}
func (UnimplementedDynamicsrvServer) Focus(context.Context, *FocusRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Focus not implemented")
}
func (UnimplementedDynamicsrvServer) HasFocus(context.Context, *FocusRequest) (*HasFocusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasFocus not implemented")
}
func (UnimplementedDynamicsrvServer) Share(context.Context, *ShareRequest) (*APICommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Share not implemented")
}
func (UnimplementedDynamicsrvServer) FocusList(context.Context, *FocusListRequest) (*FocusListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FocusList not implemented")
}
func (UnimplementedDynamicsrvServer) FansList(context.Context, *FansListRequest) (*FansListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FansList not implemented")
}
func (UnimplementedDynamicsrvServer) mustEmbedUnimplementedDynamicsrvServer() {}

// UnsafeDynamicsrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamicsrvServer will
// result in compilation errors.
type UnsafeDynamicsrvServer interface {
	mustEmbedUnimplementedDynamicsrvServer()
}

func RegisterDynamicsrvServer(s grpc.ServiceRegistrar, srv DynamicsrvServer) {
	s.RegisterService(&Dynamicsrv_ServiceDesc, srv)
}

func _Dynamicsrv_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_RefreshSupclubDynamic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSupclubDynamicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).RefreshSupclubDynamic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_RefreshSupclubDynamic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).RefreshSupclubDynamic(ctx, req.(*RefreshSupclubDynamicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_Praise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PraiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Praise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Praise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Praise(ctx, req.(*PraiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_HasPraise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasPraiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).HasPraise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_HasPraise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).HasPraise(ctx, req.(*HasPraiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Collect(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_HasCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).HasCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_HasCollect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).HasCollect(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_CollectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).CollectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_CollectList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).CollectList(ctx, req.(*CollectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_Focus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FocusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Focus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Focus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Focus(ctx, req.(*FocusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_HasFocus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FocusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).HasFocus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_HasFocus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).HasFocus(ctx, req.(*FocusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_Share_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).Share(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_Share_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).Share(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_FocusList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FocusListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).FocusList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_FocusList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).FocusList(ctx, req.(*FocusListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamicsrv_FansList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FansListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicsrvServer).FansList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamicsrv_FansList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicsrvServer).FansList(ctx, req.(*FansListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dynamicsrv_ServiceDesc is the grpc.ServiceDesc for Dynamicsrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dynamicsrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamicsrv.Dynamicsrv",
	HandlerType: (*DynamicsrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Dynamicsrv_Publish_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Dynamicsrv_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Dynamicsrv_List_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Dynamicsrv_Info_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Dynamicsrv_Delete_Handler,
		},
		{
			MethodName: "RefreshSupclubDynamic",
			Handler:    _Dynamicsrv_RefreshSupclubDynamic_Handler,
		},
		{
			MethodName: "Praise",
			Handler:    _Dynamicsrv_Praise_Handler,
		},
		{
			MethodName: "HasPraise",
			Handler:    _Dynamicsrv_HasPraise_Handler,
		},
		{
			MethodName: "Collect",
			Handler:    _Dynamicsrv_Collect_Handler,
		},
		{
			MethodName: "HasCollect",
			Handler:    _Dynamicsrv_HasCollect_Handler,
		},
		{
			MethodName: "CollectList",
			Handler:    _Dynamicsrv_CollectList_Handler,
		},
		{
			MethodName: "Focus",
			Handler:    _Dynamicsrv_Focus_Handler,
		},
		{
			MethodName: "HasFocus",
			Handler:    _Dynamicsrv_HasFocus_Handler,
		},
		{
			MethodName: "Share",
			Handler:    _Dynamicsrv_Share_Handler,
		},
		{
			MethodName: "FocusList",
			Handler:    _Dynamicsrv_FocusList_Handler,
		},
		{
			MethodName: "FansList",
			Handler:    _Dynamicsrv_FansList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dynamicsrv.proto",
}
