// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: proto/dynamicsrv.proto

package dynamicsrv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{0}
}

type APIError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`      //错误码 0正常
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"` //错误消息
}

func (x *APIError) Reset() {
	*x = APIError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIError) ProtoMessage() {}

func (x *APIError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIError.ProtoReflect.Descriptor instead.
func (*APIError) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{1}
}

func (x *APIError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *APIError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type APICommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *APIError `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Data  string    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *APICommonResponse) Reset() {
	*x = APICommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APICommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICommonResponse) ProtoMessage() {}

func (x *APICommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICommonResponse.ProtoReflect.Descriptor instead.
func (*APICommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{2}
}

func (x *APICommonResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *APICommonResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int64   `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`        //动态类型（0：普通用户动态，2:长文
	Text    *string `protobuf:"bytes,2,opt,name=Text,proto3,oneof" json:"Text,omitempty"`   //内容（动态text，imgs必填一个，长
	Imgs    *string `protobuf:"bytes,3,opt,name=Imgs,proto3,oneof" json:"Imgs,omitempty"`   //图片（长文必填）
	ImgType int64   `protobuf:"varint,4,opt,name=ImgType,proto3" json:"ImgType,omitempty"`  //0多图 1是横图 2是竖图，前端布局使
	Link    string  `protobuf:"bytes,5,opt,name=Link,proto3" json:"Link,omitempty"`         //链接
	TbMids  string  `protobuf:"bytes,6,opt,name=TbMids,proto3" json:"TbMids,omitempty"`     //同步到部落，多个用, 号隔开
	Title   *string `protobuf:"bytes,7,opt,name=Title,proto3,oneof" json:"Title,omitempty"` //标题（文章类型传）
	UserId  int64   `protobuf:"varint,8,opt,name=UserId,proto3" json:"UserId,omitempty"`    //发表动态的用户ID
	Media   string  `protobuf:"bytes,9,opt,name=Media,proto3" json:"Media,omitempty"`       //新版本新增图片列表
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{3}
}

func (x *PublishRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PublishRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *PublishRequest) GetImgs() string {
	if x != nil && x.Imgs != nil {
		return *x.Imgs
	}
	return ""
}

func (x *PublishRequest) GetImgType() int64 {
	if x != nil {
		return x.ImgType
	}
	return 0
}

func (x *PublishRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PublishRequest) GetTbMids() string {
	if x != nil {
		return x.TbMids
	}
	return ""
}

func (x *PublishRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *PublishRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishRequest) GetMedia() string {
	if x != nil {
		return x.Media
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicId int64           `protobuf:"varint,1,opt,name=DynamicId,proto3" json:"DynamicId,omitempty"` //动态ID
	Data      *PublishRequest `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`            //更新的数据
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetDynamicId() int64 {
	if x != nil {
		return x.DynamicId
	}
	return 0
}

func (x *UpdateRequest) GetData() *PublishRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page        int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`               //当前页
	TbMid       int64 `protobuf:"varint,2,opt,name=TbMid,proto3" json:"TbMid,omitempty"`             //部落id
	IsRecommend int64 `protobuf:"varint,3,opt,name=IsRecommend,proto3" json:"IsRecommend,omitempty"` //是否推荐 0否 1是
	Type        int64 `protobuf:"varint,4,opt,name=Type,proto3" json:"Type,omitempty"`               //0按时间排序 1按热度排序
	UserId      int64 `protobuf:"varint,5,opt,name=UserId,proto3" json:"UserId,omitempty"`           //用户个人收藏列表
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetTbMid() int64 {
	if x != nil {
		return x.TbMid
	}
	return 0
}

func (x *ListRequest) GetIsRecommend() int64 {
	if x != nil {
		return x.IsRecommend
	}
	return 0
}

func (x *ListRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*InfoResponse `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Error *APIError       `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetList() []*InfoResponse {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type InfoForm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicUid int64 `protobuf:"varint,1,opt,name=DynamicUid,proto3" json:"DynamicUid,omitempty"` //动态发布者uid,用于查找分表
	DynamicId  int64 `protobuf:"varint,2,opt,name=DynamicId,proto3" json:"DynamicId,omitempty"`   //动态id
	Status     int64 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`         //动态状态
	UserId     int64 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`         //用户ID用于判断是否有点赞、收藏
}

func (x *InfoForm) Reset() {
	*x = InfoForm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoForm) ProtoMessage() {}

func (x *InfoForm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoForm.ProtoReflect.Descriptor instead.
func (*InfoForm) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{7}
}

func (x *InfoForm) GetDynamicUid() int64 {
	if x != nil {
		return x.DynamicUid
	}
	return 0
}

func (x *InfoForm) GetDynamicId() int64 {
	if x != nil {
		return x.DynamicId
	}
	return 0
}

func (x *InfoForm) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InfoForm) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type InfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*InfoForm `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{8}
}

func (x *InfoRequest) GetInfos() []*InfoForm {
	if x != nil {
		return x.Infos
	}
	return nil
}

type Ext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
}

func (x *Ext) Reset() {
	*x = Ext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ext) ProtoMessage() {}

func (x *Ext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ext.ProtoReflect.Descriptor instead.
func (*Ext) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{9}
}

func (x *Ext) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

// 部落信息
type SupClub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`        //部落ID
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`     //部落名称
	Avatar string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"` //部落头像链接
	Desc   string `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`     //部落描述
}

func (x *SupClub) Reset() {
	*x = SupClub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupClub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupClub) ProtoMessage() {}

func (x *SupClub) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupClub.ProtoReflect.Descriptor instead.
func (*SupClub) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{10}
}

func (x *SupClub) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SupClub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SupClub) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *SupClub) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type InfoResponseForm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int64  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`                // 用户ID
	Type          int64  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`                    // 动态类型（0：普通用户动态，1：抖音链接，2长文）
	Title         string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`                   // 标题
	Desc          string `protobuf:"bytes,5,opt,name=Desc,proto3" json:"Desc,omitempty"`                     // 描述信息
	Imgs          string `protobuf:"bytes,6,opt,name=Imgs,proto3" json:"Imgs,omitempty"`                     // 封面图片
	Etime         int64  `protobuf:"varint,7,opt,name=Etime,proto3" json:"Etime,omitempty"`                  // 最后编辑时间
	Status        int64  `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`                // 文章状态（-1已删除,0编辑中，1已发布）
	Ext           string `protobuf:"bytes,9,opt,name=Ext,proto3" json:"Ext,omitempty"`                       // 扩展信息(json格式存储)
	ToDownloadNum int64  `protobuf:"varint,10,opt,name=ToDownloadNum,proto3" json:"ToDownloadNum,omitempty"` // 链接跳转下载次数
	ToAppNum      int64  `protobuf:"varint,11,opt,name=ToAppNum,proto3" json:"ToAppNum,omitempty"`           // 链接跳转app次数
	ToH5Num       int64  `protobuf:"varint,12,opt,name=ToH5Num,proto3" json:"ToH5Num,omitempty"`             // 打开h5分享链接
	ImgType       int64  `protobuf:"varint,13,opt,name=ImgType,proto3" json:"ImgType,omitempty"`             // 客户端布局处理（0 多图 1横图 2竖图）
	Ctime         int64  `protobuf:"varint,14,opt,name=Ctime,proto3" json:"Ctime,omitempty"`                 // 发表时间
	Media         string `protobuf:"bytes,15,opt,name=Media,proto3" json:"Media,omitempty"`                  // 媒体资源
	HasCollect    int64  `protobuf:"varint,16,opt,name=HasCollect,proto3" json:"HasCollect,omitempty"`       //是否已经收藏
	HasPraised    int64  `protobuf:"varint,17,opt,name=HasPraised,proto3" json:"HasPraised,omitempty"`       //是否已经点赞
	HasFocus      int64  `protobuf:"varint,18,opt,name=HasFocus,proto3" json:"HasFocus,omitempty"`           //是否已经关注
	PraiseCount   int64  `protobuf:"varint,19,opt,name=PraiseCount,proto3" json:"PraiseCount,omitempty"`     //点赞总数
	CommentCount  int64  `protobuf:"varint,20,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`   //评论总数
	CollectCount  int64  `protobuf:"varint,21,opt,name=CollectCount,proto3" json:"CollectCount,omitempty"`   //收藏总数
	TbMids        string `protobuf:"bytes,22,opt,name=TbMids,proto3" json:"TbMids,omitempty"`                //同步到到部落ID ->根据部落ID查询部落信息，对外是否可见
	Nick          string `protobuf:"bytes,23,opt,name=Nick,proto3" json:"Nick,omitempty"`                    //昵称 -> 调用 用户服务查询用户信息
	Avatar        string `protobuf:"bytes,24,opt,name=Avatar,proto3" json:"Avatar,omitempty"`                //头像 -> 调用 用户服务查询用户信息
}

func (x *InfoResponseForm) Reset() {
	*x = InfoResponseForm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponseForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponseForm) ProtoMessage() {}

func (x *InfoResponseForm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponseForm.ProtoReflect.Descriptor instead.
func (*InfoResponseForm) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{11}
}

func (x *InfoResponseForm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InfoResponseForm) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InfoResponseForm) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InfoResponseForm) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InfoResponseForm) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *InfoResponseForm) GetImgs() string {
	if x != nil {
		return x.Imgs
	}
	return ""
}

func (x *InfoResponseForm) GetEtime() int64 {
	if x != nil {
		return x.Etime
	}
	return 0
}

func (x *InfoResponseForm) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InfoResponseForm) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *InfoResponseForm) GetToDownloadNum() int64 {
	if x != nil {
		return x.ToDownloadNum
	}
	return 0
}

func (x *InfoResponseForm) GetToAppNum() int64 {
	if x != nil {
		return x.ToAppNum
	}
	return 0
}

func (x *InfoResponseForm) GetToH5Num() int64 {
	if x != nil {
		return x.ToH5Num
	}
	return 0
}

func (x *InfoResponseForm) GetImgType() int64 {
	if x != nil {
		return x.ImgType
	}
	return 0
}

func (x *InfoResponseForm) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *InfoResponseForm) GetMedia() string {
	if x != nil {
		return x.Media
	}
	return ""
}

func (x *InfoResponseForm) GetHasCollect() int64 {
	if x != nil {
		return x.HasCollect
	}
	return 0
}

func (x *InfoResponseForm) GetHasPraised() int64 {
	if x != nil {
		return x.HasPraised
	}
	return 0
}

func (x *InfoResponseForm) GetHasFocus() int64 {
	if x != nil {
		return x.HasFocus
	}
	return 0
}

func (x *InfoResponseForm) GetPraiseCount() int64 {
	if x != nil {
		return x.PraiseCount
	}
	return 0
}

func (x *InfoResponseForm) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *InfoResponseForm) GetCollectCount() int64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *InfoResponseForm) GetTbMids() string {
	if x != nil {
		return x.TbMids
	}
	return ""
}

func (x *InfoResponseForm) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *InfoResponseForm) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*InfoResponseForm `protobuf:"bytes,1,rep,name=Infos,proto3" json:"Infos,omitempty"`
	Error *APIError           `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"` //公共响应错误
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{12}
}

func (x *InfoResponse) GetInfos() []*InfoResponseForm {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *InfoResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicUid int64 `protobuf:"varint,1,opt,name=DynamicUid,proto3" json:"DynamicUid,omitempty"` //发布者uid,用于查找分表
	DynamicId  int64 `protobuf:"varint,2,opt,name=DynamicId,proto3" json:"DynamicId,omitempty"`   //动态id
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRequest) GetDynamicUid() int64 {
	if x != nil {
		return x.DynamicUid
	}
	return 0
}

func (x *DeleteRequest) GetDynamicId() int64 {
	if x != nil {
		return x.DynamicId
	}
	return 0
}

// 点赞请求
type PraiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicId  int64 `protobuf:"varint,1,opt,name=DynamicId,proto3" json:"DynamicId,omitempty"`   //动态ID
	DynamicUid int64 `protobuf:"varint,2,opt,name=DynamicUid,proto3" json:"DynamicUid,omitempty"` //动态发布者UID
	IsDel      int64 `protobuf:"varint,3,opt,name=IsDel,proto3" json:"IsDel,omitempty"`           // 0 点赞 1 取消
	CommentId  int64 `protobuf:"varint,4,opt,name=CommentId,proto3" json:"CommentId,omitempty"`   //评论ID（如果点赞的是评论评论那么是0
	UserId     int64 `protobuf:"varint,5,opt,name=UserId,proto3" json:"UserId,omitempty"`         //点赞者UID
}

func (x *PraiseRequest) Reset() {
	*x = PraiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseRequest) ProtoMessage() {}

func (x *PraiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseRequest.ProtoReflect.Descriptor instead.
func (*PraiseRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{14}
}

func (x *PraiseRequest) GetDynamicId() int64 {
	if x != nil {
		return x.DynamicId
	}
	return 0
}

func (x *PraiseRequest) GetDynamicUid() int64 {
	if x != nil {
		return x.DynamicUid
	}
	return 0
}

func (x *PraiseRequest) GetIsDel() int64 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

func (x *PraiseRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *PraiseRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 是否有点赞请求
type HasPraiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasPraise []*PraiseRequest `protobuf:"bytes,1,rep,name=HasPraise,proto3" json:"HasPraise,omitempty"`
}

func (x *HasPraiseRequest) Reset() {
	*x = HasPraiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasPraiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPraiseRequest) ProtoMessage() {}

func (x *HasPraiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPraiseRequest.ProtoReflect.Descriptor instead.
func (*HasPraiseRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{15}
}

func (x *HasPraiseRequest) GetHasPraise() []*PraiseRequest {
	if x != nil {
		return x.HasPraise
	}
	return nil
}

type HasPraise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicId  int64 `protobuf:"varint,1,opt,name=DynamicId,proto3" json:"DynamicId,omitempty"`   //动态ID
	DynamicUid int64 `protobuf:"varint,2,opt,name=DynamicUid,proto3" json:"DynamicUid,omitempty"` //动态发布者UID
	CommentId  int64 `protobuf:"varint,3,opt,name=CommentId,proto3" json:"CommentId,omitempty"`   //评论ID（如果点赞的是评论评论那么是0
	IsDel      int64 `protobuf:"varint,4,opt,name=IsDel,proto3" json:"IsDel,omitempty"`           // true 已点赞 false 未点赞
}

func (x *HasPraise) Reset() {
	*x = HasPraise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasPraise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPraise) ProtoMessage() {}

func (x *HasPraise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPraise.ProtoReflect.Descriptor instead.
func (*HasPraise) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{16}
}

func (x *HasPraise) GetDynamicId() int64 {
	if x != nil {
		return x.DynamicId
	}
	return 0
}

func (x *HasPraise) GetDynamicUid() int64 {
	if x != nil {
		return x.DynamicUid
	}
	return 0
}

func (x *HasPraise) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *HasPraise) GetIsDel() int64 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

type HasPraiseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasPraise []*HasPraise `protobuf:"bytes,1,rep,name=HasPraise,proto3" json:"HasPraise,omitempty"`
	Error     *APIError    `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *HasPraiseResponse) Reset() {
	*x = HasPraiseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasPraiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPraiseResponse) ProtoMessage() {}

func (x *HasPraiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPraiseResponse.ProtoReflect.Descriptor instead.
func (*HasPraiseResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{17}
}

func (x *HasPraiseResponse) GetHasPraise() []*HasPraise {
	if x != nil {
		return x.HasPraise
	}
	return nil
}

func (x *HasPraiseResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type CollectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicId  int64 `protobuf:"varint,1,opt,name=DynamicId,proto3" json:"DynamicId,omitempty"`   //动态ID
	DynamicUid int64 `protobuf:"varint,2,opt,name=DynamicUid,proto3" json:"DynamicUid,omitempty"` //动态发布者UID
	IsDel      int64 `protobuf:"varint,3,opt,name=IsDel,proto3" json:"IsDel,omitempty"`           // 0收藏 1取消收藏
	UserId     int64 `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`         //收藏者UID
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{18}
}

func (x *CollectRequest) GetDynamicId() int64 {
	if x != nil {
		return x.DynamicId
	}
	return 0
}

func (x *CollectRequest) GetDynamicUid() int64 {
	if x != nil {
		return x.DynamicUid
	}
	return 0
}

func (x *CollectRequest) GetIsDel() int64 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

func (x *CollectRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type HasCollectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDel int64     `protobuf:"varint,1,opt,name=IsDel,proto3" json:"IsDel,omitempty"` // 0 已收藏 1未收藏
	Error *APIError `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *HasCollectResponse) Reset() {
	*x = HasCollectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasCollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasCollectResponse) ProtoMessage() {}

func (x *HasCollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasCollectResponse.ProtoReflect.Descriptor instead.
func (*HasCollectResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{19}
}

func (x *HasCollectResponse) GetIsDel() int64 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

func (x *HasCollectResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type FocusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OUid  int64 `protobuf:"varint,1,opt,name=OUid,proto3" json:"OUid,omitempty"`   //被关注的uid
	UID   int64 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`     //关注者的uid
	IsDel int64 `protobuf:"varint,3,opt,name=IsDel,proto3" json:"IsDel,omitempty"` // 0关注 1取消关注
}

func (x *FocusRequest) Reset() {
	*x = FocusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusRequest) ProtoMessage() {}

func (x *FocusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusRequest.ProtoReflect.Descriptor instead.
func (*FocusRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{20}
}

func (x *FocusRequest) GetOUid() int64 {
	if x != nil {
		return x.OUid
	}
	return 0
}

func (x *FocusRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *FocusRequest) GetIsDel() int64 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

type HasFocusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDel int64     `protobuf:"varint,1,opt,name=IsDel,proto3" json:"IsDel,omitempty"` //true 已关注 false未关注
	Error *APIError `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *HasFocusResponse) Reset() {
	*x = HasFocusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasFocusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasFocusResponse) ProtoMessage() {}

func (x *HasFocusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasFocusResponse.ProtoReflect.Descriptor instead.
func (*HasFocusResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{21}
}

func (x *HasFocusResponse) GetIsDel() int64 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

func (x *HasFocusResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ShareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShareRequest) Reset() {
	*x = ShareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRequest) ProtoMessage() {}

func (x *ShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRequest.ProtoReflect.Descriptor instead.
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{22}
}

type FocusListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //用户ID
	Page   int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`     //页码
}

func (x *FocusListRequest) Reset() {
	*x = FocusListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocusListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusListRequest) ProtoMessage() {}

func (x *FocusListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusListRequest.ProtoReflect.Descriptor instead.
func (*FocusListRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{23}
}

func (x *FocusListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FocusListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FocusList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //用户ID
	Nick   string `protobuf:"bytes,2,opt,name=Nick,proto3" json:"Nick,omitempty"`      //昵称
	Avatar string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`  //头像链接地址
	Status int64  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"` // 1 关注 2 相互关注
}

func (x *FocusList) Reset() {
	*x = FocusList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusList) ProtoMessage() {}

func (x *FocusList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusList.ProtoReflect.Descriptor instead.
func (*FocusList) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{24}
}

func (x *FocusList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FocusList) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *FocusList) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FocusList) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FocusListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*FocusList `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`    //关注列表
	Count int64        `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"` //关注总数
	Error *APIError    `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *FocusListResponse) Reset() {
	*x = FocusListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocusListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusListResponse) ProtoMessage() {}

func (x *FocusListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusListResponse.ProtoReflect.Descriptor instead.
func (*FocusListResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{25}
}

func (x *FocusListResponse) GetList() []*FocusList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *FocusListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FocusListResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type FansListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //用户ID
	Page   int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`     //页码
}

func (x *FansListRequest) Reset() {
	*x = FansListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FansListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListRequest) ProtoMessage() {}

func (x *FansListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListRequest.ProtoReflect.Descriptor instead.
func (*FansListRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{26}
}

func (x *FansListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FansListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FansList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //用户ID
	Nick   string `protobuf:"bytes,2,opt,name=Nick,proto3" json:"Nick,omitempty"`      //昵称
	Avatar string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`  //头像链接地址
	Status int64  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"` // 1 关注 2 相互关注
}

func (x *FansList) Reset() {
	*x = FansList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FansList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansList) ProtoMessage() {}

func (x *FansList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansList.ProtoReflect.Descriptor instead.
func (*FansList) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{27}
}

func (x *FansList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FansList) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *FansList) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FansList) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FansListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*FansList `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`    //粉丝列表
	Count int64       `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"` //粉丝总数
	Error *APIError   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *FansListResponse) Reset() {
	*x = FansListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FansListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListResponse) ProtoMessage() {}

func (x *FansListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListResponse.ProtoReflect.Descriptor instead.
func (*FansListResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{28}
}

func (x *FansListResponse) GetList() []*FansList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *FansListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FansListResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type CollectListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //用户ID
	Page   int64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`     //页码
}

func (x *CollectListRequest) Reset() {
	*x = CollectListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectListRequest) ProtoMessage() {}

func (x *CollectListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectListRequest.ProtoReflect.Descriptor instead.
func (*CollectListRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{29}
}

func (x *CollectListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type CollectListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*InfoResponse `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Error *APIError       `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *CollectListResponse) Reset() {
	*x = CollectListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectListResponse) ProtoMessage() {}

func (x *CollectListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectListResponse.ProtoReflect.Descriptor instead.
func (*CollectListResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{30}
}

func (x *CollectListResponse) GetList() []*InfoResponse {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CollectListResponse) GetError() *APIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type RefreshSupclubDynamicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TbMids int64 `protobuf:"varint,1,opt,name=TbMids,proto3" json:"TbMids,omitempty"` //部落ID 字符串,分割
}

func (x *RefreshSupclubDynamicRequest) Reset() {
	*x = RefreshSupclubDynamicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dynamicsrv_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshSupclubDynamicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSupclubDynamicRequest) ProtoMessage() {}

func (x *RefreshSupclubDynamicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynamicsrv_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSupclubDynamicRequest.ProtoReflect.Descriptor instead.
func (*RefreshSupclubDynamicRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynamicsrv_proto_rawDescGZIP(), []int{31}
}

func (x *RefreshSupclubDynamicRequest) GetTbMids() int64 {
	if x != nil {
		return x.TbMids
	}
	return 0
}

var File_proto_dynamicsrv_proto protoreflect.FileDescriptor

var file_proto_dynamicsrv_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73,
	0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x73, 0x72, 0x76, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x38, 0x0a,
	0x08, 0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x53, 0x0a, 0x11, 0x41, 0x50, 0x49, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x81, 0x02, 0x0a,
	0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04,
	0x49, 0x6d, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x49, 0x6d,
	0x67, 0x73, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x49, 0x6d, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c,
	0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x54, 0x65, 0x78, 0x74, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x49, 0x6d, 0x67, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x5d, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x12,
	0x2e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x85, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x49, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73,
	0x72, 0x76, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72,
	0x76, 0x2e, 0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x78, 0x0a, 0x08, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x1e, 0x0a,
	0x0a, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x55, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x0b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72, 0x6d, 0x52,
	0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x19, 0x0a, 0x03, 0x45, 0x78, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e,
	0x6b, 0x22, 0x59, 0x0a, 0x07, 0x53, 0x75, 0x70, 0x43, 0x6c, 0x75, 0x62, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x22, 0xf8, 0x04, 0x0a,
	0x10, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x6f, 0x72,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6d, 0x67, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6d, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x45, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x78, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x54,
	0x6f, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x54, 0x6f, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4e, 0x75,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x41, 0x70, 0x70, 0x4e, 0x75, 0x6d, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x6f, 0x41, 0x70, 0x70, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x54, 0x6f, 0x48, 0x35, 0x4e, 0x75, 0x6d, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x54, 0x6f, 0x48, 0x35, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x49, 0x6d, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x43, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x1e, 0x0a,
	0x0a, 0x48, 0x61, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x48, 0x61, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x48, 0x61, 0x73, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x48, 0x61, 0x73, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x61,
	0x69, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x13, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x73, 0x18, 0x16, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x69, 0x63, 0x6b, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x18, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x6e, 0x0a, 0x0c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x73, 0x72, 0x76, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x55, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x61, 0x69, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x4b, 0x0a, 0x10, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61,
	0x69, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x09, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x22,
	0x7d, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x55, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x22, 0x74,
	0x0a, 0x11, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x73, 0x72, 0x76, 0x2e, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x09, 0x48,
	0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x7c, 0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x55,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x56, 0x0a, 0x12, 0x48, 0x61, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x12, 0x2a,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4a, 0x0a, 0x0c, 0x46, 0x6f,
	0x63, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4f, 0x55,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x4f, 0x55, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x22, 0x54, 0x0a, 0x10, 0x48, 0x61, 0x73, 0x46, 0x6f, 0x63,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73,
	0x44, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x49, 0x73, 0x44, 0x65, 0x6c,
	0x12, 0x2a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x0e, 0x0a, 0x0c,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x10,
	0x46, 0x6f, 0x63, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x22, 0x67, 0x0a, 0x09,
	0x46, 0x6f, 0x63, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x11, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3d, 0x0a, 0x0f, 0x46, 0x61, 0x6e, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x22, 0x66, 0x0a, 0x08, 0x46, 0x61, 0x6e, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x69, 0x63, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x7e, 0x0a, 0x10, 0x46, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x46,
	0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e,
	0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x40, 0x0a, 0x12, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x22, 0x6f, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x73, 0x72, 0x76, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73,
	0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x36, 0x0a, 0x1c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x53, 0x75, 0x70,
	0x63, 0x6c, 0x75, 0x62, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x73, 0x32, 0xf9, 0x08, 0x0a, 0x0a, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x12, 0x44, 0x0a, 0x07, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x12, 0x1a, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72,
	0x76, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50,
	0x49, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72,
	0x76, 0x2e, 0x41, 0x50, 0x49, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72,
	0x76, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x73, 0x72, 0x76, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a,
	0x15, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x53, 0x75, 0x70, 0x63, 0x6c, 0x75, 0x62, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x28, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x73, 0x72, 0x76, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x53, 0x75, 0x70, 0x63, 0x6c,
	0x75, 0x62, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50,
	0x49, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x06, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x12, 0x19, 0x2e, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72,
	0x76, 0x2e, 0x41, 0x50, 0x49, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x12, 0x1c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x48, 0x61,
	0x73, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x48, 0x61, 0x73, 0x50,
	0x72, 0x61, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a,
	0x07, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72,
	0x76, 0x2e, 0x41, 0x50, 0x49, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0a, 0x48, 0x61, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x12, 0x1a, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x48, 0x61, 0x73, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a,
	0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a,
	0x05, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x73, 0x72, 0x76, 0x2e, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x50,
	0x49, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73,
	0x72, 0x76, 0x2e, 0x48, 0x61, 0x73, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x73, 0x72, 0x76, 0x2e, 0x41, 0x50, 0x49, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e,
	0x46, 0x6f, 0x63, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x46, 0x6f,
	0x63, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x08, 0x46, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x46, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x46, 0x61, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x73, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dynamicsrv_proto_rawDescOnce sync.Once
	file_proto_dynamicsrv_proto_rawDescData = file_proto_dynamicsrv_proto_rawDesc
)

func file_proto_dynamicsrv_proto_rawDescGZIP() []byte {
	file_proto_dynamicsrv_proto_rawDescOnce.Do(func() {
		file_proto_dynamicsrv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dynamicsrv_proto_rawDescData)
	})
	return file_proto_dynamicsrv_proto_rawDescData
}

var file_proto_dynamicsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_dynamicsrv_proto_goTypes = []interface{}{
	(*Empty)(nil),                        // 0: dynamicsrv.Empty
	(*APIError)(nil),                     // 1: dynamicsrv.APIError
	(*APICommonResponse)(nil),            // 2: dynamicsrv.APICommonResponse
	(*PublishRequest)(nil),               // 3: dynamicsrv.PublishRequest
	(*UpdateRequest)(nil),                // 4: dynamicsrv.UpdateRequest
	(*ListRequest)(nil),                  // 5: dynamicsrv.ListRequest
	(*ListResponse)(nil),                 // 6: dynamicsrv.ListResponse
	(*InfoForm)(nil),                     // 7: dynamicsrv.InfoForm
	(*InfoRequest)(nil),                  // 8: dynamicsrv.InfoRequest
	(*Ext)(nil),                          // 9: dynamicsrv.Ext
	(*SupClub)(nil),                      // 10: dynamicsrv.SupClub
	(*InfoResponseForm)(nil),             // 11: dynamicsrv.InfoResponseForm
	(*InfoResponse)(nil),                 // 12: dynamicsrv.InfoResponse
	(*DeleteRequest)(nil),                // 13: dynamicsrv.DeleteRequest
	(*PraiseRequest)(nil),                // 14: dynamicsrv.PraiseRequest
	(*HasPraiseRequest)(nil),             // 15: dynamicsrv.HasPraiseRequest
	(*HasPraise)(nil),                    // 16: dynamicsrv.HasPraise
	(*HasPraiseResponse)(nil),            // 17: dynamicsrv.HasPraiseResponse
	(*CollectRequest)(nil),               // 18: dynamicsrv.CollectRequest
	(*HasCollectResponse)(nil),           // 19: dynamicsrv.HasCollectResponse
	(*FocusRequest)(nil),                 // 20: dynamicsrv.FocusRequest
	(*HasFocusResponse)(nil),             // 21: dynamicsrv.HasFocusResponse
	(*ShareRequest)(nil),                 // 22: dynamicsrv.ShareRequest
	(*FocusListRequest)(nil),             // 23: dynamicsrv.FocusListRequest
	(*FocusList)(nil),                    // 24: dynamicsrv.FocusList
	(*FocusListResponse)(nil),            // 25: dynamicsrv.FocusListResponse
	(*FansListRequest)(nil),              // 26: dynamicsrv.FansListRequest
	(*FansList)(nil),                     // 27: dynamicsrv.FansList
	(*FansListResponse)(nil),             // 28: dynamicsrv.FansListResponse
	(*CollectListRequest)(nil),           // 29: dynamicsrv.CollectListRequest
	(*CollectListResponse)(nil),          // 30: dynamicsrv.CollectListResponse
	(*RefreshSupclubDynamicRequest)(nil), // 31: dynamicsrv.RefreshSupclubDynamicRequest
}
var file_proto_dynamicsrv_proto_depIdxs = []int32{
	1,  // 0: dynamicsrv.APICommonResponse.Error:type_name -> dynamicsrv.APIError
	3,  // 1: dynamicsrv.UpdateRequest.Data:type_name -> dynamicsrv.PublishRequest
	12, // 2: dynamicsrv.ListResponse.List:type_name -> dynamicsrv.InfoResponse
	1,  // 3: dynamicsrv.ListResponse.Error:type_name -> dynamicsrv.APIError
	7,  // 4: dynamicsrv.InfoRequest.infos:type_name -> dynamicsrv.InfoForm
	11, // 5: dynamicsrv.InfoResponse.Infos:type_name -> dynamicsrv.InfoResponseForm
	1,  // 6: dynamicsrv.InfoResponse.Error:type_name -> dynamicsrv.APIError
	14, // 7: dynamicsrv.HasPraiseRequest.HasPraise:type_name -> dynamicsrv.PraiseRequest
	16, // 8: dynamicsrv.HasPraiseResponse.HasPraise:type_name -> dynamicsrv.HasPraise
	1,  // 9: dynamicsrv.HasPraiseResponse.Error:type_name -> dynamicsrv.APIError
	1,  // 10: dynamicsrv.HasCollectResponse.Error:type_name -> dynamicsrv.APIError
	1,  // 11: dynamicsrv.HasFocusResponse.Error:type_name -> dynamicsrv.APIError
	24, // 12: dynamicsrv.FocusListResponse.List:type_name -> dynamicsrv.FocusList
	1,  // 13: dynamicsrv.FocusListResponse.Error:type_name -> dynamicsrv.APIError
	27, // 14: dynamicsrv.FansListResponse.List:type_name -> dynamicsrv.FansList
	1,  // 15: dynamicsrv.FansListResponse.Error:type_name -> dynamicsrv.APIError
	12, // 16: dynamicsrv.CollectListResponse.List:type_name -> dynamicsrv.InfoResponse
	1,  // 17: dynamicsrv.CollectListResponse.Error:type_name -> dynamicsrv.APIError
	3,  // 18: dynamicsrv.Dynamicsrv.Publish:input_type -> dynamicsrv.PublishRequest
	4,  // 19: dynamicsrv.Dynamicsrv.Update:input_type -> dynamicsrv.UpdateRequest
	5,  // 20: dynamicsrv.Dynamicsrv.List:input_type -> dynamicsrv.ListRequest
	8,  // 21: dynamicsrv.Dynamicsrv.Info:input_type -> dynamicsrv.InfoRequest
	13, // 22: dynamicsrv.Dynamicsrv.Delete:input_type -> dynamicsrv.DeleteRequest
	31, // 23: dynamicsrv.Dynamicsrv.RefreshSupclubDynamic:input_type -> dynamicsrv.RefreshSupclubDynamicRequest
	14, // 24: dynamicsrv.Dynamicsrv.Praise:input_type -> dynamicsrv.PraiseRequest
	15, // 25: dynamicsrv.Dynamicsrv.HasPraise:input_type -> dynamicsrv.HasPraiseRequest
	18, // 26: dynamicsrv.Dynamicsrv.Collect:input_type -> dynamicsrv.CollectRequest
	18, // 27: dynamicsrv.Dynamicsrv.HasCollect:input_type -> dynamicsrv.CollectRequest
	29, // 28: dynamicsrv.Dynamicsrv.CollectList:input_type -> dynamicsrv.CollectListRequest
	20, // 29: dynamicsrv.Dynamicsrv.Focus:input_type -> dynamicsrv.FocusRequest
	20, // 30: dynamicsrv.Dynamicsrv.HasFocus:input_type -> dynamicsrv.FocusRequest
	22, // 31: dynamicsrv.Dynamicsrv.Share:input_type -> dynamicsrv.ShareRequest
	23, // 32: dynamicsrv.Dynamicsrv.FocusList:input_type -> dynamicsrv.FocusListRequest
	26, // 33: dynamicsrv.Dynamicsrv.FansList:input_type -> dynamicsrv.FansListRequest
	2,  // 34: dynamicsrv.Dynamicsrv.Publish:output_type -> dynamicsrv.APICommonResponse
	2,  // 35: dynamicsrv.Dynamicsrv.Update:output_type -> dynamicsrv.APICommonResponse
	6,  // 36: dynamicsrv.Dynamicsrv.List:output_type -> dynamicsrv.ListResponse
	12, // 37: dynamicsrv.Dynamicsrv.Info:output_type -> dynamicsrv.InfoResponse
	2,  // 38: dynamicsrv.Dynamicsrv.Delete:output_type -> dynamicsrv.APICommonResponse
	2,  // 39: dynamicsrv.Dynamicsrv.RefreshSupclubDynamic:output_type -> dynamicsrv.APICommonResponse
	2,  // 40: dynamicsrv.Dynamicsrv.Praise:output_type -> dynamicsrv.APICommonResponse
	17, // 41: dynamicsrv.Dynamicsrv.HasPraise:output_type -> dynamicsrv.HasPraiseResponse
	2,  // 42: dynamicsrv.Dynamicsrv.Collect:output_type -> dynamicsrv.APICommonResponse
	19, // 43: dynamicsrv.Dynamicsrv.HasCollect:output_type -> dynamicsrv.HasCollectResponse
	30, // 44: dynamicsrv.Dynamicsrv.CollectList:output_type -> dynamicsrv.CollectListResponse
	2,  // 45: dynamicsrv.Dynamicsrv.Focus:output_type -> dynamicsrv.APICommonResponse
	21, // 46: dynamicsrv.Dynamicsrv.HasFocus:output_type -> dynamicsrv.HasFocusResponse
	2,  // 47: dynamicsrv.Dynamicsrv.Share:output_type -> dynamicsrv.APICommonResponse
	25, // 48: dynamicsrv.Dynamicsrv.FocusList:output_type -> dynamicsrv.FocusListResponse
	28, // 49: dynamicsrv.Dynamicsrv.FansList:output_type -> dynamicsrv.FansListResponse
	34, // [34:50] is the sub-list for method output_type
	18, // [18:34] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_dynamicsrv_proto_init() }
func file_proto_dynamicsrv_proto_init() {
	if File_proto_dynamicsrv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dynamicsrv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APICommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoForm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupClub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponseForm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasPraiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasPraise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasPraiseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasCollectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasFocusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocusListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocusList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocusListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FansListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FansList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FansListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dynamicsrv_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshSupclubDynamicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_dynamicsrv_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dynamicsrv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dynamicsrv_proto_goTypes,
		DependencyIndexes: file_proto_dynamicsrv_proto_depIdxs,
		MessageInfos:      file_proto_dynamicsrv_proto_msgTypes,
	}.Build()
	File_proto_dynamicsrv_proto = out.File
	file_proto_dynamicsrv_proto_rawDesc = nil
	file_proto_dynamicsrv_proto_goTypes = nil
	file_proto_dynamicsrv_proto_depIdxs = nil
}
