// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: define/userinfo.proto

package userinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUserType int32

const (
	SetUserType_SetInfoAdd         SetUserType = 0
	SetUserType_SetInfoNick        SetUserType = 1
	SetUserType_SetInfoDesc        SetUserType = 2
	SetUserType_SetInfoAvatar      SetUserType = 3
	SetUserType_SetInfoReset       SetUserType = 4
	SetUserType_SetInfoDel         SetUserType = 5
	SetUserType_SetConfAsset       SetUserType = 6
	SetUserType_SetConfNotice      SetUserType = 7
	SetUserType_SetConfDynamicShow SetUserType = 8
	SetUserType_SetConfStrangeMsg  SetUserType = 9
	SetUserType_SetConfCover       SetUserType = 10
	SetUserType_SetConfLan         SetUserType = 11
	SetUserType_SetconfIsSearch    SetUserType = 12
	SetUserType_SetRelationShow    SetUserType = 13
)

// Enum value maps for SetUserType.
var (
	SetUserType_name = map[int32]string{
		0:  "SetInfoAdd",
		1:  "SetInfoNick",
		2:  "SetInfoDesc",
		3:  "SetInfoAvatar",
		4:  "SetInfoReset",
		5:  "SetInfoDel",
		6:  "SetConfAsset",
		7:  "SetConfNotice",
		8:  "SetConfDynamicShow",
		9:  "SetConfStrangeMsg",
		10: "SetConfCover",
		11: "SetConfLan",
		12: "SetconfIsSearch",
		13: "SetRelationShow",
	}
	SetUserType_value = map[string]int32{
		"SetInfoAdd":         0,
		"SetInfoNick":        1,
		"SetInfoDesc":        2,
		"SetInfoAvatar":      3,
		"SetInfoReset":       4,
		"SetInfoDel":         5,
		"SetConfAsset":       6,
		"SetConfNotice":      7,
		"SetConfDynamicShow": 8,
		"SetConfStrangeMsg":  9,
		"SetConfCover":       10,
		"SetConfLan":         11,
		"SetconfIsSearch":    12,
		"SetRelationShow":    13,
	}
)

func (x SetUserType) Enum() *SetUserType {
	p := new(SetUserType)
	*p = x
	return p
}

func (x SetUserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetUserType) Descriptor() protoreflect.EnumDescriptor {
	return file_define_userinfo_proto_enumTypes[0].Descriptor()
}

func (SetUserType) Type() protoreflect.EnumType {
	return &file_define_userinfo_proto_enumTypes[0]
}

func (x SetUserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetUserType.Descriptor instead.
func (SetUserType) EnumDescriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{0}
}

type UserConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID          string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Asset           int32  `protobuf:"varint,2,opt,name=Asset,proto3" json:"Asset,omitempty"`                     //资产展示设置：0关闭；1开启
	IsSearch        int32  `protobuf:"varint,3,opt,name=IsSearch,proto3" json:"IsSearch,omitempty"`               //nft头像展示：0关闭，1开启
	TribeNoticeType int32  `protobuf:"varint,4,opt,name=TribeNoticeType,proto3" json:"TribeNoticeType,omitempty"` //部落消息通知设置：0接受全部，
	DynamicShow     int32  `protobuf:"varint,5,opt,name=DynamicShow,proto3" json:"DynamicShow,omitempty"`         //动态展示设置：0关闭，1开启
	StrangeMsg      int32  `protobuf:"varint,6,opt,name=StrangeMsg,proto3" json:"StrangeMsg,omitempty"`           //默生人私信是否限制：0不限制，1限制
	Cover           string `protobuf:"bytes,7,opt,name=Cover,proto3" json:"Cover,omitempty"`                      //  用户资料卡封面
	Lan             string `protobuf:"bytes,8,opt,name=Lan,proto3" json:"Lan,omitempty"`
	RelationShow    int32  `protobuf:"varint,9,opt,name=RelationShow,proto3" json:"RelationShow,omitempty"` //是否展示粉丝关注列表
}

func (x *UserConf) Reset() {
	*x = UserConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConf) ProtoMessage() {}

func (x *UserConf) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConf.ProtoReflect.Descriptor instead.
func (*UserConf) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{0}
}

func (x *UserConf) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserConf) GetAsset() int32 {
	if x != nil {
		return x.Asset
	}
	return 0
}

func (x *UserConf) GetIsSearch() int32 {
	if x != nil {
		return x.IsSearch
	}
	return 0
}

func (x *UserConf) GetTribeNoticeType() int32 {
	if x != nil {
		return x.TribeNoticeType
	}
	return 0
}

func (x *UserConf) GetDynamicShow() int32 {
	if x != nil {
		return x.DynamicShow
	}
	return 0
}

func (x *UserConf) GetStrangeMsg() int32 {
	if x != nil {
		return x.StrangeMsg
	}
	return 0
}

func (x *UserConf) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *UserConf) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

func (x *UserConf) GetRelationShow() int32 {
	if x != nil {
		return x.RelationShow
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Avatar   string `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Nick     string `protobuf:"bytes,3,opt,name=Nick,proto3" json:"Nick,omitempty"`
	Age      int32  `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	Sex      int32  `protobuf:"varint,5,opt,name=Sex,proto3" json:"Sex,omitempty"`
	CTime    int64  `protobuf:"varint,6,opt,name=CTime,proto3" json:"CTime,omitempty"`
	Desc     string `protobuf:"bytes,7,opt,name=Desc,proto3" json:"Desc,omitempty"`          //简介
	IsFrozen int32  `protobuf:"varint,8,opt,name=IsFrozen,proto3" json:"IsFrozen,omitempty"` //帐号是否被系统冻结
	Wallet   string `protobuf:"bytes,9,opt,name=Wallet,proto3" json:"Wallet,omitempty"`      //钱包地址
	IsPwd    int32  `protobuf:"varint,10,opt,name=IsPwd,proto3" json:"IsPwd,omitempty"`      //是否设置密码
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfo) GetCTime() int64 {
	if x != nil {
		return x.CTime
	}
	return 0
}

func (x *UserInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UserInfo) GetIsFrozen() int32 {
	if x != nil {
		return x.IsFrozen
	}
	return 0
}

func (x *UserInfo) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *UserInfo) GetIsPwd() int32 {
	if x != nil {
		return x.IsPwd
	}
	return 0
}

// 用户综合信息，包括info，conf，relation
type UserInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string    `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Info   *UserInfo `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	Conf   *UserConf `protobuf:"bytes,3,opt,name=Conf,proto3" json:"Conf,omitempty"`
}

func (x *UserInfos) Reset() {
	*x = UserInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfos) ProtoMessage() {}

func (x *UserInfos) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfos.ProtoReflect.Descriptor instead.
func (*UserInfos) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfos) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfos) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UserInfos) GetConf() *UserConf {
	if x != nil {
		return x.Conf
	}
	return nil
}

type UserResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret     int32  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *UserResult) Reset() {
	*x = UserResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResult) ProtoMessage() {}

func (x *UserResult) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResult.ProtoReflect.Descriptor instead.
func (*UserResult) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{3}
}

func (x *UserResult) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *UserResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUsersInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIDs []string `protobuf:"bytes,1,rep,name=UserIDs,proto3" json:"UserIDs,omitempty"`
}

func (x *GetUsersInfoReq) Reset() {
	*x = GetUsersInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoReq) ProtoMessage() {}

func (x *GetUsersInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoReq.ProtoReflect.Descriptor instead.
func (*GetUsersInfoReq) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersInfoReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type GetUsersInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *UserResult `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Users  []*UserInfo `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty"`
}

func (x *GetUsersInfoResp) Reset() {
	*x = GetUsersInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoResp) ProtoMessage() {}

func (x *GetUsersInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoResp.ProtoReflect.Descriptor instead.
func (*GetUsersInfoResp) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersInfoResp) GetResult() *UserResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUsersInfoResp) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// 查询用户设置信息，包括设置
type GetUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //查询用户
	Ouids  []string `protobuf:"bytes,2,rep,name=Ouids,proto3" json:"Ouids,omitempty"`   //目标用户
	Fields string   `protobuf:"bytes,3,opt,name=Fields,proto3" json:"Fields,omitempty"` //info,conf, 两种可选,逗号分隔,如果查询用户关系，请在上层api层调用通讯录查询
}

func (x *GetUsersReq) Reset() {
	*x = GetUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersReq) ProtoMessage() {}

func (x *GetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersReq.ProtoReflect.Descriptor instead.
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUsersReq) GetOuids() []string {
	if x != nil {
		return x.Ouids
	}
	return nil
}

func (x *GetUsersReq) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

type GetUsersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *UserResult  `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Users  []*UserInfos `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty"`
}

func (x *GetUsersResp) Reset() {
	*x = GetUsersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResp) ProtoMessage() {}

func (x *GetUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResp.ProtoReflect.Descriptor instead.
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersResp) GetResult() *UserResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUsersResp) GetUsers() []*UserInfos {
	if x != nil {
		return x.Users
	}
	return nil
}

// 设置密码重新设置
type RestUsersPwdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //查询用户
	Pwd    string `protobuf:"bytes,2,opt,name=Pwd,proto3" json:"Pwd,omitempty"`       //新密码
	OPwd   string `protobuf:"bytes,3,opt,name=OPwd,proto3" json:"OPwd,omitempty"`     //旧密码
	NPwd   string `protobuf:"bytes,4,opt,name=NPwd,proto3" json:"NPwd,omitempty"`     //新密码（新密码）
}

func (x *RestUsersPwdReq) Reset() {
	*x = RestUsersPwdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestUsersPwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestUsersPwdReq) ProtoMessage() {}

func (x *RestUsersPwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestUsersPwdReq.ProtoReflect.Descriptor instead.
func (*RestUsersPwdReq) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{8}
}

func (x *RestUsersPwdReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RestUsersPwdReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *RestUsersPwdReq) GetOPwd() string {
	if x != nil {
		return x.OPwd
	}
	return ""
}

func (x *RestUsersPwdReq) GetNPwd() string {
	if x != nil {
		return x.NPwd
	}
	return ""
}

type RestUsersPwdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *UserResult `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *RestUsersPwdResp) Reset() {
	*x = RestUsersPwdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestUsersPwdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestUsersPwdResp) ProtoMessage() {}

func (x *RestUsersPwdResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestUsersPwdResp.ProtoReflect.Descriptor instead.
func (*RestUsersPwdResp) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{9}
}

func (x *RestUsersPwdResp) GetResult() *UserResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type SetUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetType SetUserType `protobuf:"varint,1,opt,name=SetType,proto3,enum=userinfo.SetUserType" json:"SetType,omitempty"`
	Info    *UserInfo   `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	Conf    *UserConf   `protobuf:"bytes,3,opt,name=Conf,proto3" json:"Conf,omitempty"`
}

func (x *SetUserInfoReq) Reset() {
	*x = SetUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserInfoReq) ProtoMessage() {}

func (x *SetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserInfoReq.ProtoReflect.Descriptor instead.
func (*SetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{10}
}

func (x *SetUserInfoReq) GetSetType() SetUserType {
	if x != nil {
		return x.SetType
	}
	return SetUserType_SetInfoAdd
}

func (x *SetUserInfoReq) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SetUserInfoReq) GetConf() *UserConf {
	if x != nil {
		return x.Conf
	}
	return nil
}

type SetUserInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *UserResult `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *SetUserInfoResp) Reset() {
	*x = SetUserInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userinfo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserInfoResp) ProtoMessage() {}

func (x *SetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userinfo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserInfoResp.ProtoReflect.Descriptor instead.
func (*SetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_define_userinfo_proto_rawDescGZIP(), []int{11}
}

func (x *SetUserInfoResp) GetResult() *UserResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_define_userinfo_proto protoreflect.FileDescriptor

var file_define_userinfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x8c, 0x02, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x49, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x49, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x72, 0x69, 0x62,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x54, 0x72, 0x69, 0x62, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x68, 0x6f,
	0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x53, 0x68, 0x6f, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x4d,
	0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x61, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x77, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x77,
	0x22, 0xe6, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x69, 0x63,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x41, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x12,
	0x1a, 0x0a, 0x08, 0x49, 0x73, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x49, 0x73, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x50, 0x77, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x49, 0x73, 0x50, 0x77, 0x64, 0x22, 0x73, 0x0a, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x26,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x22, 0x38,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x73, 0x22, 0x6a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x22, 0x53, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x75, 0x69, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x75, 0x69, 0x64, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x67, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x63, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x77, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x77,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x77, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4f, 0x50, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4f, 0x50, 0x77, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x50, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x50, 0x77, 0x64, 0x22, 0x40, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x2f, 0x0a, 0x07, 0x53, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x07, 0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x26, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x22, 0x3f, 0x0a, 0x0f, 0x53, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x94, 0x02, 0x0a, 0x0b,
	0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x64, 0x64, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x69, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x73, 0x63, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x10, 0x03,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c,
	0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x68, 0x6f, 0x77, 0x10, 0x08, 0x12,
	0x15, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x4d, 0x73, 0x67, 0x10, 0x09, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x4c, 0x61, 0x6e, 0x10, 0x0b, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x63,
	0x6f, 0x6e, 0x66, 0x49, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x10, 0x0c, 0x12, 0x13, 0x0a,
	0x0f, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x77,
	0x10, 0x0d, 0x32, 0x96, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0c, 0x67,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x39, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x15,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a,
	0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x77, 0x64, 0x12, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x50, 0x77, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_define_userinfo_proto_rawDescOnce sync.Once
	file_define_userinfo_proto_rawDescData = file_define_userinfo_proto_rawDesc
)

func file_define_userinfo_proto_rawDescGZIP() []byte {
	file_define_userinfo_proto_rawDescOnce.Do(func() {
		file_define_userinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_define_userinfo_proto_rawDescData)
	})
	return file_define_userinfo_proto_rawDescData
}

var file_define_userinfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_define_userinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_define_userinfo_proto_goTypes = []interface{}{
	(SetUserType)(0),         // 0: userinfo.SetUserType
	(*UserConf)(nil),         // 1: userinfo.UserConf
	(*UserInfo)(nil),         // 2: userinfo.UserInfo
	(*UserInfos)(nil),        // 3: userinfo.UserInfos
	(*UserResult)(nil),       // 4: userinfo.UserResult
	(*GetUsersInfoReq)(nil),  // 5: userinfo.GetUsersInfoReq
	(*GetUsersInfoResp)(nil), // 6: userinfo.GetUsersInfoResp
	(*GetUsersReq)(nil),      // 7: userinfo.GetUsersReq
	(*GetUsersResp)(nil),     // 8: userinfo.GetUsersResp
	(*RestUsersPwdReq)(nil),  // 9: userinfo.RestUsersPwdReq
	(*RestUsersPwdResp)(nil), // 10: userinfo.RestUsersPwdResp
	(*SetUserInfoReq)(nil),   // 11: userinfo.SetUserInfoReq
	(*SetUserInfoResp)(nil),  // 12: userinfo.SetUserInfoResp
}
var file_define_userinfo_proto_depIdxs = []int32{
	2,  // 0: userinfo.UserInfos.Info:type_name -> userinfo.UserInfo
	1,  // 1: userinfo.UserInfos.Conf:type_name -> userinfo.UserConf
	4,  // 2: userinfo.GetUsersInfoResp.Result:type_name -> userinfo.UserResult
	2,  // 3: userinfo.GetUsersInfoResp.Users:type_name -> userinfo.UserInfo
	4,  // 4: userinfo.GetUsersResp.Result:type_name -> userinfo.UserResult
	3,  // 5: userinfo.GetUsersResp.Users:type_name -> userinfo.UserInfos
	4,  // 6: userinfo.RestUsersPwdResp.Result:type_name -> userinfo.UserResult
	0,  // 7: userinfo.SetUserInfoReq.SetType:type_name -> userinfo.SetUserType
	2,  // 8: userinfo.SetUserInfoReq.Info:type_name -> userinfo.UserInfo
	1,  // 9: userinfo.SetUserInfoReq.Conf:type_name -> userinfo.UserConf
	4,  // 10: userinfo.SetUserInfoResp.Result:type_name -> userinfo.UserResult
	5,  // 11: userinfo.User.getUsersInfo:input_type -> userinfo.GetUsersInfoReq
	7,  // 12: userinfo.User.getUsers:input_type -> userinfo.GetUsersReq
	11, // 13: userinfo.User.updateUserInfo:input_type -> userinfo.SetUserInfoReq
	9,  // 14: userinfo.User.ResetUserPwd:input_type -> userinfo.RestUsersPwdReq
	6,  // 15: userinfo.User.getUsersInfo:output_type -> userinfo.GetUsersInfoResp
	8,  // 16: userinfo.User.getUsers:output_type -> userinfo.GetUsersResp
	12, // 17: userinfo.User.updateUserInfo:output_type -> userinfo.SetUserInfoResp
	10, // 18: userinfo.User.ResetUserPwd:output_type -> userinfo.RestUsersPwdResp
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_define_userinfo_proto_init() }
func file_define_userinfo_proto_init() {
	if File_define_userinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_define_userinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestUsersPwdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestUsersPwdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userinfo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_define_userinfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_define_userinfo_proto_goTypes,
		DependencyIndexes: file_define_userinfo_proto_depIdxs,
		EnumInfos:         file_define_userinfo_proto_enumTypes,
		MessageInfos:      file_define_userinfo_proto_msgTypes,
	}.Build()
	File_define_userinfo_proto = out.File
	file_define_userinfo_proto_rawDesc = nil
	file_define_userinfo_proto_goTypes = nil
	file_define_userinfo_proto_depIdxs = nil
}
