// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: define/pack.v1.proto

package pack

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPackDetailParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MorderNo  string `protobuf:"bytes,1,opt,name=MorderNo,proto3" json:"MorderNo,omitempty"`   //主表唯一ID
	Page      uint64 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`          //页码
	PageSize  uint64 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`  //每页条数
	UserID    int64  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`      //用户id
	PackMsgID string `protobuf:"bytes,5,opt,name=PackMsgID,proto3" json:"PackMsgID,omitempty"` //红包对应的消息id
}

func (x *GetPackDetailParams) Reset() {
	*x = GetPackDetailParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPackDetailParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackDetailParams) ProtoMessage() {}

func (x *GetPackDetailParams) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackDetailParams.ProtoReflect.Descriptor instead.
func (*GetPackDetailParams) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GetPackDetailParams) GetMorderNo() string {
	if x != nil {
		return x.MorderNo
	}
	return ""
}

func (x *GetPackDetailParams) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPackDetailParams) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPackDetailParams) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetPackDetailParams) GetPackMsgID() string {
	if x != nil {
		return x.PackMsgID
	}
	return ""
}

type PackInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID           int64             `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`                                                                                         //红包主人id
	Avatar           string            `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`                                                                                          //红包主人头像
	Name             string            `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                                                                              //红包主人用户名
	Token            string            `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`                                                                                            //红包货币名
	Status           int64             `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`                                                                                         //红包状态 1=制作中 2=可领取 3 =已领完 4=红包已过期 (-1,-2,-3)=制作失败
	Content          string            `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`                                                                                        //红包寄语
	AllNum           int64             `protobuf:"varint,7,opt,name=AllNum,proto3" json:"AllNum,omitempty"`                                                                                         //红包总数
	RNum             int64             `protobuf:"varint,8,opt,name=RNum,proto3" json:"RNum,omitempty"`                                                                                             //红包已领取数
	AllBalance       string            `protobuf:"bytes,9,opt,name=AllBalance,proto3" json:"AllBalance,omitempty"`                                                                                  //总金额
	RBalance         string            `protobuf:"bytes,10,opt,name=RBalance,proto3" json:"RBalance,omitempty"`                                                                                     //已领取金额
	IsReceive        int64             `protobuf:"varint,11,opt,name=IsReceive,proto3" json:"IsReceive,omitempty"`                                                                                  //是否已领取1是0否
	PayType          int64             `protobuf:"varint,12,opt,name=PayType,proto3" json:"PayType,omitempty"`                                                                                      //红包支付类型 1 钱包 2余额
	IsSend           int64             `protobuf:"varint,13,opt,name=IsSend,proto3" json:"IsSend,omitempty"`                                                                                        //发红包状态 0:待发放 1:已发
	ImID             string            `protobuf:"bytes,14,opt,name=ImID,proto3" json:"ImID,omitempty"`                                                                                             //群聊唯一id
	ConversationType int64             `protobuf:"varint,15,opt,name=ConversationType,proto3" json:"ConversationType,omitempty"`                                                                    //会话类型1：单聊 3-群聊
	MapID            string            `protobuf:"bytes,16,opt,name=MapID,proto3" json:"MapID,omitempty"`                                                                                           //im映射id
	RoomID           map[string]string `protobuf:"bytes,17,rep,name=RoomID,proto3" json:"RoomID,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //房间id
	Icon             string            `protobuf:"bytes,18,opt,name=Icon,proto3" json:"Icon,omitempty"`                                                                                             //红包货币icon
	Entrance         string            `protobuf:"bytes,19,opt,name=Entrance,proto3" json:"Entrance,omitempty"`                                                                                     // 创建入口
	Chain            int64             `protobuf:"varint,20,opt,name=Chain,proto3" json:"Chain,omitempty"`                                                                                          // 红包货币
	CType            int64             `protobuf:"varint,21,opt,name=CType,proto3" json:"CType,omitempty"`                                                                                          // 红包类型（1：拼手气，2:普通红包）
	Balance          string            `protobuf:"bytes,22,opt,name=Balance,proto3" json:"Balance,omitempty"`                                                                                       // 用户领取金额
	CTime            int64             `protobuf:"varint,23,opt,name=CTime,proto3" json:"CTime,omitempty"`
	OrderNo          string            `protobuf:"bytes,24,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	Contract         string            `protobuf:"bytes,25,opt,name=Contract,proto3" json:"Contract,omitempty"`
}

func (x *PackInfo) Reset() {
	*x = PackInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackInfo) ProtoMessage() {}

func (x *PackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackInfo.ProtoReflect.Descriptor instead.
func (*PackInfo) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{1}
}

func (x *PackInfo) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PackInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PackInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PackInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PackInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PackInfo) GetAllNum() int64 {
	if x != nil {
		return x.AllNum
	}
	return 0
}

func (x *PackInfo) GetRNum() int64 {
	if x != nil {
		return x.RNum
	}
	return 0
}

func (x *PackInfo) GetAllBalance() string {
	if x != nil {
		return x.AllBalance
	}
	return ""
}

func (x *PackInfo) GetRBalance() string {
	if x != nil {
		return x.RBalance
	}
	return ""
}

func (x *PackInfo) GetIsReceive() int64 {
	if x != nil {
		return x.IsReceive
	}
	return 0
}

func (x *PackInfo) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *PackInfo) GetIsSend() int64 {
	if x != nil {
		return x.IsSend
	}
	return 0
}

func (x *PackInfo) GetImID() string {
	if x != nil {
		return x.ImID
	}
	return ""
}

func (x *PackInfo) GetConversationType() int64 {
	if x != nil {
		return x.ConversationType
	}
	return 0
}

func (x *PackInfo) GetMapID() string {
	if x != nil {
		return x.MapID
	}
	return ""
}

func (x *PackInfo) GetRoomID() map[string]string {
	if x != nil {
		return x.RoomID
	}
	return nil
}

func (x *PackInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PackInfo) GetEntrance() string {
	if x != nil {
		return x.Entrance
	}
	return ""
}

func (x *PackInfo) GetChain() int64 {
	if x != nil {
		return x.Chain
	}
	return 0
}

func (x *PackInfo) GetCType() int64 {
	if x != nil {
		return x.CType
	}
	return 0
}

func (x *PackInfo) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *PackInfo) GetCTime() int64 {
	if x != nil {
		return x.CTime
	}
	return 0
}

func (x *PackInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PackInfo) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type PackListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MorderNo string `protobuf:"bytes,1,opt,name=MorderNo,proto3" json:"MorderNo,omitempty"` //	主表唯一ID
	OrderNo  string `protobuf:"bytes,2,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`   //红包列表唯一ID
	UserID   int64  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`    //领取用户id
	Avatar   string `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`     //领取人头像
	Name     string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`         //领取人用户名
	Balance  string `protobuf:"bytes,6,opt,name=Balance,proto3" json:"Balance,omitempty"`   //领取金额
	Time     int64  `protobuf:"varint,7,opt,name=Time,proto3" json:"Time,omitempty"`        //领取时间
	Lucky    int64  `protobuf:"varint,8,opt,name=Lucky,proto3" json:"Lucky,omitempty"`      //运气王 1=是 0不是
	IsSend   int64  `protobuf:"varint,9,opt,name=IsSend,proto3" json:"IsSend,omitempty"`    //发红包状态 0:待发放 1:已发
}

func (x *PackListItem) Reset() {
	*x = PackListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackListItem) ProtoMessage() {}

func (x *PackListItem) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackListItem.ProtoReflect.Descriptor instead.
func (*PackListItem) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{2}
}

func (x *PackListItem) GetMorderNo() string {
	if x != nil {
		return x.MorderNo
	}
	return ""
}

func (x *PackListItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PackListItem) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PackListItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PackListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackListItem) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *PackListItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PackListItem) GetLucky() int64 {
	if x != nil {
		return x.Lucky
	}
	return 0
}

func (x *PackListItem) GetIsSend() int64 {
	if x != nil {
		return x.IsSend
	}
	return 0
}

type GetPackDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count        int64           `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	PackInfo     *PackInfo       `protobuf:"bytes,2,opt,name=PackInfo,proto3" json:"PackInfo,omitempty"`
	PackListItem []*PackListItem `protobuf:"bytes,3,rep,name=PackListItem,proto3" json:"PackListItem,omitempty"`
}

func (x *GetPackDetailResp) Reset() {
	*x = GetPackDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPackDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackDetailResp) ProtoMessage() {}

func (x *GetPackDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackDetailResp.ProtoReflect.Descriptor instead.
func (*GetPackDetailResp) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GetPackDetailResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetPackDetailResp) GetPackInfo() *PackInfo {
	if x != nil {
		return x.PackInfo
	}
	return nil
}

func (x *GetPackDetailResp) GetPackListItem() []*PackListItem {
	if x != nil {
		return x.PackListItem
	}
	return nil
}

type AwardPackParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MorderNo string `protobuf:"bytes,1,opt,name=MorderNo,proto3" json:"MorderNo,omitempty"` //主表唯一ID
	UserID   int64  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`    //用户id
	SessID   string `protobuf:"bytes,3,opt,name=SessID,proto3" json:"SessID,omitempty"`     // 用户缓存
}

func (x *AwardPackParams) Reset() {
	*x = AwardPackParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwardPackParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwardPackParams) ProtoMessage() {}

func (x *AwardPackParams) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwardPackParams.ProtoReflect.Descriptor instead.
func (*AwardPackParams) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{4}
}

func (x *AwardPackParams) GetMorderNo() string {
	if x != nil {
		return x.MorderNo
	}
	return ""
}

func (x *AwardPackParams) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AwardPackParams) GetSessID() string {
	if x != nil {
		return x.SessID
	}
	return ""
}

type AwardPackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReceive int64 `protobuf:"varint,1,opt,name=IsReceive,proto3" json:"IsReceive,omitempty"` //是否领取成功 1-领取成功 0-失败
	Status    int64 `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`       //红包状态 1-创建中 2-领奖中 3-已领完 4-红包已过期 -1-创建红包失败 -2-红包金额不足 -3-手续费金额不足 -10-重新发送后老红包删除作废
}

func (x *AwardPackResp) Reset() {
	*x = AwardPackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwardPackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwardPackResp) ProtoMessage() {}

func (x *AwardPackResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwardPackResp.ProtoReflect.Descriptor instead.
func (*AwardPackResp) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{5}
}

func (x *AwardPackResp) GetIsReceive() int64 {
	if x != nil {
		return x.IsReceive
	}
	return 0
}

func (x *AwardPackResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreatePackParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`        //用户id
	Num      int64   `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`              //红包数量
	Amount   string  `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`         //红包金额
	Content  *string `protobuf:"bytes,4,opt,name=Content,proto3,oneof" json:"Content,omitempty"` //红包内容
	Chain    int64   `protobuf:"varint,5,opt,name=Chain,proto3" json:"Chain,omitempty"`          //币种
	Entrance string  `protobuf:"bytes,6,opt,name=Entrance,proto3" json:"Entrance,omitempty"`     //创建入口（1：频道，2：发现入口，3:普通群聊, 4:单聊）
	CType    int64   `protobuf:"varint,7,opt,name=CType,proto3" json:"CType,omitempty"`          //红包类型（1：拼手气，2:普通红包）
	TbMid    *string `protobuf:"bytes,8,opt,name=TbMid,proto3,oneof" json:"TbMid,omitempty"`     //超级群id 创建入口是频道下 必填
	TbZid    *string `protobuf:"bytes,9,opt,name=TbZid,proto3,oneof" json:"TbZid,omitempty"`     //超级分组id 创建入口是频道下 必填
	TbCid    *string `protobuf:"bytes,10,opt,name=TbCid,proto3,oneof" json:"TbCid,omitempty"`    //超级频道id 创建入口是频道下 必填
	ImId     *string `protobuf:"bytes,11,opt,name=ImId,proto3,oneof" json:"ImId,omitempty"`      //普通群聊或者超级群频道im_id 发现入口可不填
	To       *string `protobuf:"bytes,12,opt,name=To,proto3,oneof" json:"To,omitempty"`          //钱包地址
	Set      string  `protobuf:"bytes,13,opt,name=Set,proto3" json:"Set,omitempty"`              //num 数量 amount 金额
	PayType  int64   `protobuf:"varint,14,opt,name=PayType,proto3" json:"PayType,omitempty"`     //1钱包 2余额
	MapID    *string `protobuf:"bytes,15,opt,name=MapID,proto3,oneof" json:"MapID,omitempty"`    //发现入口可不填 其他填环信id
	SessID   string  `protobuf:"bytes,16,opt,name=SessID,proto3" json:"SessID,omitempty"`        // 用户缓存
	Contract string  `protobuf:"bytes,17,opt,name=Contract,proto3" json:"Contract,omitempty"`    //代币合约
}

func (x *CreatePackParams) Reset() {
	*x = CreatePackParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackParams) ProtoMessage() {}

func (x *CreatePackParams) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackParams.ProtoReflect.Descriptor instead.
func (*CreatePackParams) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePackParams) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreatePackParams) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *CreatePackParams) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreatePackParams) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *CreatePackParams) GetChain() int64 {
	if x != nil {
		return x.Chain
	}
	return 0
}

func (x *CreatePackParams) GetEntrance() string {
	if x != nil {
		return x.Entrance
	}
	return ""
}

func (x *CreatePackParams) GetCType() int64 {
	if x != nil {
		return x.CType
	}
	return 0
}

func (x *CreatePackParams) GetTbMid() string {
	if x != nil && x.TbMid != nil {
		return *x.TbMid
	}
	return ""
}

func (x *CreatePackParams) GetTbZid() string {
	if x != nil && x.TbZid != nil {
		return *x.TbZid
	}
	return ""
}

func (x *CreatePackParams) GetTbCid() string {
	if x != nil && x.TbCid != nil {
		return *x.TbCid
	}
	return ""
}

func (x *CreatePackParams) GetImId() string {
	if x != nil && x.ImId != nil {
		return *x.ImId
	}
	return ""
}

func (x *CreatePackParams) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

func (x *CreatePackParams) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *CreatePackParams) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *CreatePackParams) GetMapID() string {
	if x != nil && x.MapID != nil {
		return *x.MapID
	}
	return ""
}

func (x *CreatePackParams) GetSessID() string {
	if x != nil {
		return x.SessID
	}
	return ""
}

func (x *CreatePackParams) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

type CreatePackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo string `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"` //红包订单号
	Status  int64  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`  //红包状态 1-创建中 2-领奖中 3-已领完 4-红包已过期 -1-创建红包失败 -2-红包金额不足 -3-手续费金额不足 -10-重新发送后老红包删除作废
}

func (x *CreatePackResp) Reset() {
	*x = CreatePackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackResp) ProtoMessage() {}

func (x *CreatePackResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackResp.ProtoReflect.Descriptor instead.
func (*CreatePackResp) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePackResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePackResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type StatLogParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api        string            `protobuf:"bytes,1,opt,name=Api,proto3" json:"Api,omitempty"`
	UserID     int64             `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ActionType string            `protobuf:"bytes,3,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	Ext        map[string]string `protobuf:"bytes,4,rep,name=Ext,proto3" json:"Ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StatLogParams) Reset() {
	*x = StatLogParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatLogParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatLogParams) ProtoMessage() {}

func (x *StatLogParams) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatLogParams.ProtoReflect.Descriptor instead.
func (*StatLogParams) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{8}
}

func (x *StatLogParams) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *StatLogParams) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *StatLogParams) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *StatLogParams) GetExt() map[string]string {
	if x != nil {
		return x.Ext
	}
	return nil
}

type StatLogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatLogResp) Reset() {
	*x = StatLogResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatLogResp) ProtoMessage() {}

func (x *StatLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatLogResp.ProtoReflect.Descriptor instead.
func (*StatLogResp) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{9}
}

type PackExpireParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackInfo *PackInfo `protobuf:"bytes,1,opt,name=PackInfo,proto3" json:"PackInfo,omitempty"`
}

func (x *PackExpireParams) Reset() {
	*x = PackExpireParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackExpireParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackExpireParams) ProtoMessage() {}

func (x *PackExpireParams) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackExpireParams.ProtoReflect.Descriptor instead.
func (*PackExpireParams) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{10}
}

func (x *PackExpireParams) GetPackInfo() *PackInfo {
	if x != nil {
		return x.PackInfo
	}
	return nil
}

type PackExpireResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *PackExpireResp) Reset() {
	*x = PackExpireResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackExpireResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackExpireResp) ProtoMessage() {}

func (x *PackExpireResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackExpireResp.ProtoReflect.Descriptor instead.
func (*PackExpireResp) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{11}
}

func (x *PackExpireResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PackListParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int64 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Page     int32 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *PackListParams) Reset() {
	*x = PackListParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackListParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackListParams) ProtoMessage() {}

func (x *PackListParams) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackListParams.ProtoReflect.Descriptor instead.
func (*PackListParams) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{12}
}

func (x *PackListParams) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PackListParams) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PackListParams) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PackListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackList []*PackInfo `protobuf:"bytes,2,rep,name=PackList,proto3" json:"PackList,omitempty"`
}

func (x *PackListResp) Reset() {
	*x = PackListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_pack_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackListResp) ProtoMessage() {}

func (x *PackListResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_pack_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackListResp.ProtoReflect.Descriptor instead.
func (*PackListResp) Descriptor() ([]byte, []int) {
	return file_define_pack_v1_proto_rawDescGZIP(), []int{13}
}

func (x *PackListResp) GetPackList() []*PackInfo {
	if x != nil {
		return x.PackList
	}
	return nil
}

var File_define_pack_v1_proto protoreflect.FileDescriptor

var file_define_pack_v1_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x69, 0x6d, 0x22, 0x97, 0x01, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x63, 0x6b, 0x4d, 0x73,
	0x67, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x63, 0x6b, 0x4d,
	0x73, 0x67, 0x49, 0x44, 0x22, 0xd3, 0x05, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41,
	0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x4e, 0x75, 0x6d, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x6c, 0x6c,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41,
	0x6c, 0x6c, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x49, 0x73, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x49,
	0x73, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6d, 0x49, 0x44, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6d, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x44, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6d,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x54, 0x79, 0x70, 0x65, 0x18, 0x15, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x43, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x17, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x43, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x18, 0x18, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18,
	0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a,
	0x39, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe4, 0x01, 0x0a, 0x0c, 0x50,
	0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x75, 0x63, 0x6b, 0x79, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x4c, 0x75, 0x63, 0x6b, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x53,
	0x65, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x49, 0x73, 0x53, 0x65, 0x6e,
	0x64, 0x22, 0x89, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a,
	0x08, 0x50, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x69, 0x6d, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x50,
	0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x69, 0x6d, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x0c, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x5d, 0x0a,
	0x0f, 0x41, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x4d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x73, 0x73, 0x49, 0x44, 0x22, 0x45, 0x0a, 0x0d,
	0x41, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x49, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x49, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0xf9, 0x03, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x63, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e,
	0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x05, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x05, 0x54, 0x62, 0x4d, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05,
	0x54, 0x62, 0x5a, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x54,
	0x62, 0x5a, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x54, 0x62, 0x43, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x54, 0x62, 0x43, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x49, 0x6d, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x04, 0x52, 0x04, 0x49, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x54,
	0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x05, 0x52, 0x02, 0x54, 0x6f, 0x88, 0x01, 0x01,
	0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53,
	0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x05,
	0x4d, 0x61, 0x70, 0x49, 0x44, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x48, 0x06, 0x52, 0x05, 0x4d,
	0x61, 0x70, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x73, 0x73, 0x49,
	0x44, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x73, 0x73, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x54, 0x62, 0x4d, 0x69,
	0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x54, 0x62, 0x5a, 0x69, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x54, 0x62, 0x43, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x49, 0x6d, 0x49, 0x64, 0x42, 0x05,
	0x0a, 0x03, 0x5f, 0x54, 0x6f, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x4d, 0x61, 0x70, 0x49, 0x44, 0x22,
	0x42, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x41, 0x70, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2c, 0x0a, 0x03, 0x45, 0x78, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69,
	0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e,
	0x45, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x45, 0x78, 0x74, 0x1a, 0x36, 0x0a,
	0x08, 0x45, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x3c, 0x0a, 0x10, 0x50, 0x61, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x69, 0x6d, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x28, 0x0a, 0x0e, 0x50, 0x61, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x56, 0x0a, 0x0e,
	0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x38, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x69, 0x6d, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xd3,
	0x02, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3f, 0x0a,
	0x0d, 0x67, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x17,
	0x2e, 0x69, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x15, 0x2e, 0x69, 0x6d, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33,
	0x0a, 0x09, 0x61, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x69, 0x6d,
	0x2e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x11, 0x2e, 0x69, 0x6d, 0x2e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63,
	0x6b, 0x12, 0x14, 0x2e, 0x69, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63,
	0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x12, 0x2e, 0x69, 0x6d, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x07, 0x73,
	0x74, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x11, 0x2e, 0x69, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x4c, 0x6f, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0f, 0x2e, 0x69, 0x6d, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x61,
	0x63, 0x6b, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x14, 0x2e, 0x69, 0x6d, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x12,
	0x2e, 0x69, 0x6d, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x2e, 0x69, 0x6d, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x10, 0x2e, 0x69, 0x6d, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_define_pack_v1_proto_rawDescOnce sync.Once
	file_define_pack_v1_proto_rawDescData = file_define_pack_v1_proto_rawDesc
)

func file_define_pack_v1_proto_rawDescGZIP() []byte {
	file_define_pack_v1_proto_rawDescOnce.Do(func() {
		file_define_pack_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_define_pack_v1_proto_rawDescData)
	})
	return file_define_pack_v1_proto_rawDescData
}

var file_define_pack_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_define_pack_v1_proto_goTypes = []interface{}{
	(*GetPackDetailParams)(nil), // 0: im.GetPackDetailParams
	(*PackInfo)(nil),            // 1: im.PackInfo
	(*PackListItem)(nil),        // 2: im.PackListItem
	(*GetPackDetailResp)(nil),   // 3: im.GetPackDetailResp
	(*AwardPackParams)(nil),     // 4: im.AwardPackParams
	(*AwardPackResp)(nil),       // 5: im.AwardPackResp
	(*CreatePackParams)(nil),    // 6: im.CreatePackParams
	(*CreatePackResp)(nil),      // 7: im.CreatePackResp
	(*StatLogParams)(nil),       // 8: im.StatLogParams
	(*StatLogResp)(nil),         // 9: im.StatLogResp
	(*PackExpireParams)(nil),    // 10: im.PackExpireParams
	(*PackExpireResp)(nil),      // 11: im.PackExpireResp
	(*PackListParams)(nil),      // 12: im.PackListParams
	(*PackListResp)(nil),        // 13: im.PackListResp
	nil,                         // 14: im.PackInfo.RoomIDEntry
	nil,                         // 15: im.StatLogParams.ExtEntry
}
var file_define_pack_v1_proto_depIdxs = []int32{
	14, // 0: im.PackInfo.RoomID:type_name -> im.PackInfo.RoomIDEntry
	1,  // 1: im.GetPackDetailResp.PackInfo:type_name -> im.PackInfo
	2,  // 2: im.GetPackDetailResp.PackListItem:type_name -> im.PackListItem
	15, // 3: im.StatLogParams.Ext:type_name -> im.StatLogParams.ExtEntry
	1,  // 4: im.PackExpireParams.PackInfo:type_name -> im.PackInfo
	1,  // 5: im.PackListResp.PackList:type_name -> im.PackInfo
	0,  // 6: im.PackServer.getPackDetail:input_type -> im.GetPackDetailParams
	4,  // 7: im.PackServer.awardPack:input_type -> im.AwardPackParams
	6,  // 8: im.PackServer.createPack:input_type -> im.CreatePackParams
	8,  // 9: im.PackServer.statLog:input_type -> im.StatLogParams
	10, // 10: im.PackServer.packExpire:input_type -> im.PackExpireParams
	12, // 11: im.PackServer.packList:input_type -> im.PackListParams
	3,  // 12: im.PackServer.getPackDetail:output_type -> im.GetPackDetailResp
	5,  // 13: im.PackServer.awardPack:output_type -> im.AwardPackResp
	7,  // 14: im.PackServer.createPack:output_type -> im.CreatePackResp
	9,  // 15: im.PackServer.statLog:output_type -> im.StatLogResp
	11, // 16: im.PackServer.packExpire:output_type -> im.PackExpireResp
	13, // 17: im.PackServer.packList:output_type -> im.PackListResp
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_define_pack_v1_proto_init() }
func file_define_pack_v1_proto_init() {
	if File_define_pack_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_define_pack_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPackDetailParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPackDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwardPackParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwardPackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatLogParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatLogResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackExpireParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackExpireResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackListParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_pack_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_define_pack_v1_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_define_pack_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_define_pack_v1_proto_goTypes,
		DependencyIndexes: file_define_pack_v1_proto_depIdxs,
		MessageInfos:      file_define_pack_v1_proto_msgTypes,
	}.Build()
	File_define_pack_v1_proto = out.File
	file_define_pack_v1_proto_rawDesc = nil
	file_define_pack_v1_proto_goTypes = nil
	file_define_pack_v1_proto_depIdxs = nil
}
