// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: define/userups.proto

package userups

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserPointsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *GetUserPointsReq) Reset() {
	*x = GetUserPointsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPointsReq) ProtoMessage() {}

func (x *GetUserPointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPointsReq.ProtoReflect.Descriptor instead.
func (*GetUserPointsReq) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserPointsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type UserPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points int64  `protobuf:"varint,1,opt,name=Points,proto3" json:"Points,omitempty"` //积分
	Level  int32  `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`   //等级
	Status string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`  //用户状态
}

func (x *UserPoint) Reset() {
	*x = UserPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPoint) ProtoMessage() {}

func (x *UserPoint) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPoint.ProtoReflect.Descriptor instead.
func (*UserPoint) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{1}
}

func (x *UserPoint) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *UserPoint) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserPoint) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserPointsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32      `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Msg    string     `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	UPoint *UserPoint `protobuf:"bytes,3,opt,name=UPoint,proto3" json:"UPoint,omitempty"`
}

func (x *GetUserPointsResp) Reset() {
	*x = GetUserPointsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPointsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPointsResp) ProtoMessage() {}

func (x *GetUserPointsResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPointsResp.ProtoReflect.Descriptor instead.
func (*GetUserPointsResp) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPointsResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetUserPointsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserPointsResp) GetUPoint() *UserPoint {
	if x != nil {
		return x.UPoint
	}
	return nil
}

type GetUserPointDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PType  string `protobuf:"bytes,2,opt,name=PType,proto3" json:"PType,omitempty"` //任务类型，默认为空
}

func (x *GetUserPointDetailsReq) Reset() {
	*x = GetUserPointDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPointDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPointDetailsReq) ProtoMessage() {}

func (x *GetUserPointDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPointDetailsReq.ProtoReflect.Descriptor instead.
func (*GetUserPointDetailsReq) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPointDetailsReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetUserPointDetailsReq) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

type PointDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PType   string `protobuf:"bytes,2,opt,name=PType,proto3" json:"PType,omitempty"`      //积分任务类型
	Amount  int64  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`   //可正可负，本次变动的积分值
	Desc    string `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`        //任务描述
	PTime   int64  `protobuf:"varint,5,opt,name=PTime,proto3" json:"PTime,omitempty"`     //获得时间
	RPoints int64  `protobuf:"varint,6,opt,name=RPoints,proto3" json:"RPoints,omitempty"` //剩余积分
}

func (x *PointDetail) Reset() {
	*x = PointDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointDetail) ProtoMessage() {}

func (x *PointDetail) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointDetail.ProtoReflect.Descriptor instead.
func (*PointDetail) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{4}
}

func (x *PointDetail) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PointDetail) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *PointDetail) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PointDetail) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PointDetail) GetPTime() int64 {
	if x != nil {
		return x.PTime
	}
	return 0
}

func (x *PointDetail) GetRPoints() int64 {
	if x != nil {
		return x.RPoints
	}
	return 0
}

type GetUserPointDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret     int32          `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Msg     string         `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Details []*PointDetail `protobuf:"bytes,3,rep,name=Details,proto3" json:"Details,omitempty"`
}

func (x *GetUserPointDetailsResp) Reset() {
	*x = GetUserPointDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPointDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPointDetailsResp) ProtoMessage() {}

func (x *GetUserPointDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPointDetailsResp.ProtoReflect.Descriptor instead.
func (*GetUserPointDetailsResp) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserPointDetailsResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetUserPointDetailsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserPointDetailsResp) GetDetails() []*PointDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

type SetUserPointReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TaskID int64 `protobuf:"varint,2,opt,name=TaskID,proto3" json:"TaskID,omitempty"` //通过taskID来限制
}

func (x *SetUserPointReq) Reset() {
	*x = SetUserPointReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserPointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPointReq) ProtoMessage() {}

func (x *SetUserPointReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPointReq.ProtoReflect.Descriptor instead.
func (*SetUserPointReq) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{6}
}

func (x *SetUserPointReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SetUserPointReq) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

type SetUserPointResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32      `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Msg    string     `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	UPoint *UserPoint `protobuf:"bytes,3,opt,name=UPoint,proto3" json:"UPoint,omitempty"`
}

func (x *SetUserPointResp) Reset() {
	*x = SetUserPointResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserPointResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPointResp) ProtoMessage() {}

func (x *SetUserPointResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPointResp.ProtoReflect.Descriptor instead.
func (*SetUserPointResp) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{7}
}

func (x *SetUserPointResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *SetUserPointResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SetUserPointResp) GetUPoint() *UserPoint {
	if x != nil {
		return x.UPoint
	}
	return nil
}

type GetUserTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TaskType string `protobuf:"bytes,2,opt,name=TaskType,proto3" json:"TaskType,omitempty"` //newuser,daily,
}

func (x *GetUserTaskReq) Reset() {
	*x = GetUserTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTaskReq) ProtoMessage() {}

func (x *GetUserTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTaskReq.ProtoReflect.Descriptor instead.
func (*GetUserTaskReq) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserTaskReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetUserTaskReq) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type PointTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID int64  `protobuf:"varint,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	TType  string `protobuf:"bytes,2,opt,name=TType,proto3" json:"TType,omitempty"`    //任务类型
	Amount int64  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"` //任务积分值，可以为负
	Desc   string `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`      //任务描述
	Status int32  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"` //任务完成状态
	UTime  int64  `protobuf:"varint,6,opt,name=UTime,proto3" json:"UTime,omitempty"`   //任务完成时间，
	Icon   string `protobuf:"bytes,7,opt,name=Icon,proto3" json:"Icon,omitempty"`      //icon
	Times  int64  `protobuf:"varint,8,opt,name=Times,proto3" json:"Times,omitempty"`   //任务已经完成次数
	Limit  int64  `protobuf:"varint,9,opt,name=Limit,proto3" json:"Limit,omitempty"`   //任务要求次数
}

func (x *PointTask) Reset() {
	*x = PointTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointTask) ProtoMessage() {}

func (x *PointTask) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointTask.ProtoReflect.Descriptor instead.
func (*PointTask) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{9}
}

func (x *PointTask) GetTaskID() int64 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

func (x *PointTask) GetTType() string {
	if x != nil {
		return x.TType
	}
	return ""
}

func (x *PointTask) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PointTask) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PointTask) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PointTask) GetUTime() int64 {
	if x != nil {
		return x.UTime
	}
	return 0
}

func (x *PointTask) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PointTask) GetTimes() int64 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *PointTask) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserTaskResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   int32        `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Msg   string       `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Tasks []*PointTask `protobuf:"bytes,3,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
}

func (x *GetUserTaskResp) Reset() {
	*x = GetUserTaskResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_define_userups_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTaskResp) ProtoMessage() {}

func (x *GetUserTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_define_userups_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTaskResp.ProtoReflect.Descriptor instead.
func (*GetUserTaskResp) Descriptor() ([]byte, []int) {
	return file_define_userups_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserTaskResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetUserTaskResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserTaskResp) GetTasks() []*PointTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_define_userups_proto protoreflect.FileDescriptor

var file_define_userups_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x22,
	0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x51, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x63,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x2a, 0x0a, 0x06, 0x55, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x55, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x54, 0x79, 0x70, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x0b,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x50, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x52, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52,
	0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x22, 0x41, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x62, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x52,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12,
	0x2a, 0x0a, 0x06, 0x55, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x06, 0x55, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x22, 0xd3, 0x01, 0x0a, 0x09, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x55, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x5f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x28,
	0x0a, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x32, 0xb3, 0x02, 0x0a, 0x07, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x70, 0x73, 0x12, 0x46, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x58, 0x0a, 0x13,
	0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x0d, 0x61, 0x64, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70,
	0x73, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x0b,
	0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x75, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_define_userups_proto_rawDescOnce sync.Once
	file_define_userups_proto_rawDescData = file_define_userups_proto_rawDesc
)

func file_define_userups_proto_rawDescGZIP() []byte {
	file_define_userups_proto_rawDescOnce.Do(func() {
		file_define_userups_proto_rawDescData = protoimpl.X.CompressGZIP(file_define_userups_proto_rawDescData)
	})
	return file_define_userups_proto_rawDescData
}

var file_define_userups_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_define_userups_proto_goTypes = []interface{}{
	(*GetUserPointsReq)(nil),        // 0: userups.GetUserPointsReq
	(*UserPoint)(nil),               // 1: userups.UserPoint
	(*GetUserPointsResp)(nil),       // 2: userups.GetUserPointsResp
	(*GetUserPointDetailsReq)(nil),  // 3: userups.GetUserPointDetailsReq
	(*PointDetail)(nil),             // 4: userups.PointDetail
	(*GetUserPointDetailsResp)(nil), // 5: userups.GetUserPointDetailsResp
	(*SetUserPointReq)(nil),         // 6: userups.SetUserPointReq
	(*SetUserPointResp)(nil),        // 7: userups.SetUserPointResp
	(*GetUserTaskReq)(nil),          // 8: userups.GetUserTaskReq
	(*PointTask)(nil),               // 9: userups.PointTask
	(*GetUserTaskResp)(nil),         // 10: userups.GetUserTaskResp
}
var file_define_userups_proto_depIdxs = []int32{
	1,  // 0: userups.GetUserPointsResp.UPoint:type_name -> userups.UserPoint
	4,  // 1: userups.GetUserPointDetailsResp.Details:type_name -> userups.PointDetail
	1,  // 2: userups.SetUserPointResp.UPoint:type_name -> userups.UserPoint
	9,  // 3: userups.GetUserTaskResp.Tasks:type_name -> userups.PointTask
	0,  // 4: userups.UserUps.getUserPoints:input_type -> userups.GetUserPointsReq
	3,  // 5: userups.UserUps.getUserPointDetails:input_type -> userups.GetUserPointDetailsReq
	6,  // 6: userups.UserUps.addUserPoints:input_type -> userups.SetUserPointReq
	8,  // 7: userups.UserUps.getUserTask:input_type -> userups.GetUserTaskReq
	2,  // 8: userups.UserUps.getUserPoints:output_type -> userups.GetUserPointsResp
	5,  // 9: userups.UserUps.getUserPointDetails:output_type -> userups.GetUserPointDetailsResp
	7,  // 10: userups.UserUps.addUserPoints:output_type -> userups.SetUserPointResp
	10, // 11: userups.UserUps.getUserTask:output_type -> userups.GetUserTaskResp
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_define_userups_proto_init() }
func file_define_userups_proto_init() {
	if File_define_userups_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_define_userups_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPointsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPointsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPointDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPointDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserPointReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserPointResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_define_userups_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTaskResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_define_userups_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_define_userups_proto_goTypes,
		DependencyIndexes: file_define_userups_proto_depIdxs,
		MessageInfos:      file_define_userups_proto_msgTypes,
	}.Build()
	File_define_userups_proto = out.File
	file_define_userups_proto_rawDesc = nil
	file_define_userups_proto_goTypes = nil
	file_define_userups_proto_depIdxs = nil
}
