name: ci

on:
  push:
    branches:
      - main
env:
  PROJECT_ID:  ${{ vars.APIFOXPROJECTID }} # Github仓库中配置的APIFOXPROJECTID
  ACCESS_TOKEN:  ${{ vars.APIFOXACCESSTOKEN }} # Github仓库中配置的APIFOXACCESSTOKEN
  ECR_REGISTRY: 024905375334.dkr.ecr.ap-southeast-1.amazonaws.com #${{ secrets.ECR_REGISTRY }}


jobs:
  syncDoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image # 构建镜像并执行
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY/common:rpclient_v1 -f deploy/docker/Dockerfile .
          docker push $ECR_REGISTRY/common:rpclient_v1
          docker run --rm -v ./api:/app/   $ECR_REGISTRY/common:rpclient_v1 /bin/sh /app/syncDoc.sh ${{ env.PROJECT_ID }} ${{ env.ACCESS_TOKEN }}