name: ci

on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID:  ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION:  ${{ vars.AWS_REGION }}
  PROJECT_ID:  ${{ vars.APIFOXPROJECTID }} # Github仓库中配置的APIFOXPROJECTID
  ACCESS_TOKEN:  ${{ vars.APIFOXACCESSTOKEN }} # Github仓库中配置的APIFOXACCESSTOKEN
  ECR_REGISTRY: 024905375334.dkr.ecr.ap-southeast-1.amazonaws.com #${{ secrets.ECR_REGISTRY }}


jobs:
  syncDoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials # 配置aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          #          role-to-assume: arn:aws:iam::024905375334:role/github-actions
          #          role-session-name: github_action_Session
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR # 终端登录ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image and run task # 构建镜像并执行
        id: build-image
        run: |
#          docker build -t $ECR_REGISTRY/common:rpclient_v1 -f deploy/docker/Dockerfile .
#          docker push $ECR_REGISTRY/common:rpclient_v1
          docker run --rm -v ./api:/app/   $ECR_REGISTRY/common:rpclient_v1 /bin/sh /app/syncDoc.sh ${{ env.PROJECT_ID }} ${{ env.ACCESS_TOKEN }}